### ISSUE TITLE
【bug】丁原的慈孝技能判定的不是义子标记而是叛弑技能

### ISSUE THREAD

**Issue by Natsukage** [libccy/noname#1021]
![c34297ce86ae0438bc9874532ee6dc65](https://github.com/libccy/noname/assets/19678081/116c2b52-89db-4495-ada1-b904018dc3e1)
按照技能说明的话，应该是有义子标记的角色获得叛弑。但是现在的结算方式则反过来了。获得叛弑技能的角色将会获得义子标记
同时，慈孝技能不是判断场上是否有人有义子标记，而是判断场上是否有人有叛弑技能。

导致如果我用蹈节丢掉了叛弑技能，会即刻失去义子标记。丁原的下个回合开始时，可以无损重新收义子。

**Comment by XboxSoldier** [comment]
因为叛弑和义子本质上是一个技能，确实应该分离出来

**Comment by XboxSoldier** [comment]
#1051
