### ISSUE TITLE
Revert官渡之战调整界袁绍主公为OL谋袁绍

### ISSUE THREAD

**Issue by lieren2023** [libccy/noname#1031]
谋袁绍与官渡之战背景不符，希望能在下一版Revert官渡之战调整界袁绍主公为OL谋袁绍（[commit 42c22bc](https://github.com/libccy/noname/commit/42c22bc1c58a61182f61378619f4aad73eb9127b)）

**Comment by Spmario233** [comment]
下版本直接开同名替换
想玩哪个袁绍玩哪个
