### ISSUE TITLE
1.9.120.1版本更新的页面点不到【确定】按钮

### ISSUE THREAD

**Issue by TianboJi** [libccy/noname#105]
如图，更新日志过长导致超出了屏幕界面，且更新窗口无法拖动，无法点击确定按钮。
![UI](https://user-images.githubusercontent.com/29609040/222937967-81f072df-ff3e-4508-a590-12ffeacfc365.jpeg)
目前已经尝试过将【选项】-【外观】-【界面缩放】设置为了80%，但这个设定对首页无效。

**Comment by Spmario233** [comment]
你用你🐎的第三方客户端
