### ISSUE TITLE
台湾神吕蒙的涉猎②的发动时机时"结束阶段", 而不是"结束阶段开始时", 这是bug吗?

### ISSUE THREAD

**Issue by lolisix** [libccy/noname#107]
首先"**结束阶段**"多为"**结束阶段开始时**"这一时机的简称, 但是**台湾神吕蒙的涉猎②**的发动时机真的就是"**结束阶段**", 而不是"结束阶段开始时", 这是bug吗?  
<br/>
此外, 台湾神吕蒙与台湾神关羽的姓不是"吕"与"关", 而是姓"神", 也就是在乱斗模式的武将搜索中, 它们两位排在"S"音标的位置, 这应该不太正常吧.

**Comment by Spmario233** [comment]
下个版本改
