### ISSUE TITLE
bug:承陈登论势摸牌数量不正确。

### ISSUE THREAD

**Issue by TruthCat** [libccy/noname#1081]
在游戏的第一轮，主公神貂蝉，二号位承陈登，三号位界孟获，四号位界大乔，五号位界甘宁，主公装备八卦阵过，二号位陈登对主公发动论势，主公一张没摸，但弃了两张。第二轮，主公有-1马，其余4人均无+1-1马，除界孟获有偃月刀陈登有连弩均无武器，陈登对主公发动论势力，应该摸4弃3，但主公只摸了3张，弃置3张。

**Comment by Spmario233** [comment]
《至多摸至五张》
