### ISSUE TITLE
导入手杀UI,游戏开局异常

### ISSUE THREAD

**Issue by Console2015** [libccy/noname#109]
游戏版本:v1.9.120.1
调试浏览器:Microsoft.Edge
我在无名杀II群下载了2023年3月5日版的“十周年UI”和“手杀UI”扩展包。
将项目克隆到本地后，先删除选项卡中原先有的扩展，重新创建了两个扩展并解压了压缩包。
执行index.html文件，选择身份场对局，“手杀UI”抛出错误:
Uncaught TypeError: game.getFileList is not a function
    at Object.loadPlugins (eval at proceed (game.js:7669:10), <anonymous>:201:9)
    at eval (eval at proceed (game.js:7669:10), <anonymous>:2777:11)
    at HTMLLinkElement.runNext (eval at proceed (game.js:7669:10), <anonymous>:321:6)

我尝试将{shizhounianUI:'十周年UI',shoushaUI:'手杀UI',}加入game/package.js/play内，错误依然存在。
后面我在群内下载Window（由理版·炽）（懒人）版软件，exe文件能正常运行，执行html文件还是爆同一个错误。
请问这个问题我该如何解决？是我导入扩展顺序出错了？还是某个配置文件需要修改？

**Comment by Cz13755172570** [comment]
大概在game.js line 7882
if(lib.device){....}else if(typeof window.require=='function'){....} else{...}
两处有定义getFileList函数，然而这两处均不满足条件，这是没有配置好导致的吗？

**Comment by Spmario233** [comment]
扩展问题 你往这报个鸡毛bug
