### ISSUE TITLE
3D刘宏的装备区里面的牌视为手牌是否是指装备区里可以存在手牌区?

### ISSUE THREAD

**Issue by lolisix** [libccy/noname#1092]
3D刘宏的装备区里面的牌视为手牌是否是指装备区里可以存在手牌?

这里的手牌我默认指手牌区, 因为弃置一张手牌和弃置一张牌的区别就是手牌只存在于手牌区.

我用凌统做了测试, 在弃牌阶段(因游戏规则而导致的那个时机点)弃置被视为手牌区里的装备牌, 竟然能触发旋风. 但是旋风描述是失去装备区里面的装备牌, 手牌区怎么可能存在于装备区里? 因此按照描述, 此时不应该能触发旋风. 当然, 我不是说现在的结算有问题, 我是建议改描述, 将其修改为:
_②其他角色的弃牌阶段, 若其处于连环状态, 其装备区里的牌计入手牌上限且其可以如手牌般弃置装备区里的牌._

**Comment by Spmario233** [comment]
别杠描述
