### ISSUE TITLE
起许劭失去技能异常、庞德公因和洽而使用的牌类型错误、郭皇后无法矫诏、杜夫人的异色的效果描述仍然错误、流年时机错误、严夫人馋逆描述错误、唐姬描述有问题、傅肜傅佥结算与新杀的不同.

### ISSUE THREAD

**Issue by lolisix** [libccy/noname#1093]
当起许劭失去技能后, 他因评鉴而能够触发的技能会永久存在, 尽管在技能栏不显示.

庞德公因和洽而使用的基本牌类型错误, 按技能描述来看, 应该是虚拟牌, 但实际上是实体牌(转化牌), 属于结算错误.

界郭皇后的队友声明一个牌名后, 郭皇后无法以矫诏的方式使用此牌(就是只能把此牌当成原牌名使用). 标郭皇后也没法用.

杜夫人的异色的描述改成了因执行杀的效果而受到的伤害, 但是武将左侧的小框上写的仍然是杀的伤害.
![](https://s2.loli.net/2024/03/17/Mk4fSqmtCTbRviG.png)

滕公主的流年的描述时机错误. 原描述是: "_锁定技.**回合结束时**,若本回合内进行了本次游戏的第一次洗牌......_", 时机应该改为**一名角色的回合结束时** 

严夫人的馋逆原描述是: "_出牌阶段限一次.你可将任意张手牌交给一名其他角色,然后其可以将**等量的手牌**当做[决斗]使用......._" 实际结算是**至多等量张手牌**. 
话说后面的摸牌弃牌时机可能还是有歧义, 我认为既可以指在决斗的结算过程中, 又可以指使用决斗后的下一个非空闲时间点, 应该强调时机名称, 从 "_若其因此[决斗]**造成了伤害**,则其摸X张牌(X为此[决斗]对应的实体牌数).若其因此[决斗]**受到过伤害**,则你弃置所有手牌._" 改为 "_当其因此[决斗]**造成伤害后**,则其摸X张牌(X为此[决斗]对应的实体牌数). 当其因此[决斗]**受到伤害后**,则你弃置所有手牌_." 
(我记得我提交过后面这个时机点的问题, 但是我当时太忙, 忘记你说什么了, 已关闭的里面没找到, 就再提一遍, 请见谅.)

唐姬的节烈原描述是 "_当你受到除自己和"抗歌"角色以外的角色造成的伤害时,你可以防止此伤害并选择一种花色,然后你失去X点体力......_"但是唐姬在指定抗歌角色前, 为什么会因为抗歌角色不存在而无法触发技能? 从描述上来看, 抗歌角色摸牌不是技能消耗, 并且这个技能根本就没有消耗, 那么无法执行的技能效果就不应该影响技能的发动. 我没有新杀帐号, 但我记得某个视频里, 唐姬在抗歌前是可以节烈的, 不过没找到这个视频, 所以我也不清楚是,,描述错误还是结算错误.

傅肜傅佥的御关结算与新杀的不同, 无名杀的结算为: _一名角色的回合结束时,若你已损失的体力值为全场最多,你可以减1点体力上限,然后**令X名角色**将手牌摸至体力上限(X为你已损失的体力值)._ 但是新杀的结算为**令至多X名角色**. 按无名杀的结算来看, 这武将还能资敌. 新杀的这个结算我能保证肯定是对的, 就不找视频了.

**Comment by mengxinzxz** [comment]
滕公主、严夫人描述问题已改，二傅效果已改，严夫人后端关于决斗的部分不受理，唐姬有亲测

**Comment by mengxinzxz** [comment]
许劭请关掉你的扩展、郭皇后转化牌是技能按钮形式的可选择式转化（若发动技能后没有转化按钮也请关掉你的扩展）、杜夫人不受理、庞德公描述问题已改

**Comment by mengxinzxz** [comment]
以后有任何问题也可直接入群872800679直接反馈给更新者，接受反馈速度更快
