### ISSUE TITLE
player.canUse的bug

### ISSUE THREAD

**Issue by Lucilor** [libccy/noname#11]
描述：如果目标(target)不能使用锦囊牌(cardEnabled为false)，那么他会被判定为锦囊牌的无效目标，即player.canUse(trick,target)=false，但手动使用锦囊可以对他使用。
栗子：如图，第一次毁灭可以指定福，第二次不能。
![qq 20180426092058](https://user-images.githubusercontent.com/12553377/39280649-2a3650d4-4933-11e8-909c-8d74d048e7be.png)

**Comment by Spmario233** [comment]
手动使用本身不在考虑范畴
需要使用之外判断
