### ISSUE TITLE
无名杀里面的回合内与回合外与回合角色是如何判定的?

### ISSUE THREAD

**Issue by lolisix** [libccy/noname#110]
&emsp;&emsp;按照规则集, 回合内与回合外是这样判定的:
![回合内](https://s2.loli.net/2023/03/31/Fteqd1MQ2upZJWj.png)
![回合外](https://s2.loli.net/2023/03/31/GgFu9bvAHqB6pPo.png)
&emsp;&emsp;估计是这样判定代码不好写, 所以网杀上的与回合内和回合外相关的描述的技能的结算一直都很混乱.
&emsp;&emsp;我在无名杀里面也做了简单的测试, 下面是我总结出的结论.
<hr/>

1. &emsp;&emsp;如果技能有发动次数限制且此发动次数限制与回合内或回合外有关, 那么此技能能够在对应的时机发动(且无视此时与回合内或回合外相关的描述), 且此次技能的发动次数计入到下一个没有被跳过的回合.  
测试对象: 界孙策、手杀皇甫嵩、张星彩.  
额外补充说明: 如果此时是一号位从背面翻至正面的过程中, 通过插入结算使手杀皇甫嵩对一号位发动技能(此时二号位武将牌正面向上), 再插入皇甫嵩的结算使二号位的武将牌背面向上, 当二号位的"回合"结束后, 此时三号位武将牌正面向上, 那么皇甫嵩的技能次数计入到三号位的回合.  
额外补充说明: 如果此时是一号位从背面翻至正面的过程中, 若一号位弃置了一张基本牌, 且下家为武将牌正面向上的张星彩, 那么张星彩能够发动甚贤.
2. &emsp;&emsp;如果技能的描述中有回合角色字样, 那么此技能能够在对应的时机发动, 且此时若下家武将牌正面向上, 那么此时回合角色为下家, 若下家武将牌背面向上, 那么与回合角色字样相关的效果无法被发动.  
测试对象: 神赵云、贾逵.  
3. &emsp;&emsp;如果技能描述中有回合字样, 那么此技能能够在对应时机发动, 且此回合为虚空回合.  
测试对象: 沙摩柯. (想不到其他与沙摩柯描述相似的武将了)  
额外补充说明: 一号位为沙摩柯-曹仁, 且沙摩柯的攻击范围为1, 且沙摩柯武将牌背面向上, 首先通过曹仁使沙摩柯使用一张无中生有, 发动一次蒺藜, 然后沙摩柯的回合被跳过, 然后二号位通过插入结算, 让沙摩柯使用一张闪, 沙摩柯又能发动一次蒺藜.   
额外补充说明: 以界曹仁-邓艾为双将时, 曹仁在发动解围移动场上的牌时, 因发动解围而弃置的牌可以触发屯田.
<hr/>

&emsp;&emsp; 我目前只能想到这些与回合有关的描述, 不知道我目前总结出来的是否合理.
如果以第1类为基准, 我认为第2类与第3类都有问题. 第2类应该把回合角色视为那个时机的逆时针数的第一个武将牌正面向上的角色(如果武将牌都是正面向上, 那么此角色就是自己). 第3类的沙摩柯应该无法在二号位发动蒺藜(因为按照第2类的测试, 沙摩柯使用无中生有时, 回合角色是二号位).
但是, 如果在第1类的第二个额外补充说明的场景中, 我认为张星彩不能发动甚贤, 因为按照第2类的测试, 一号位弃牌时, 回合角色是张星彩.
<hr/>

&emsp;&emsp; 上面那些时机都是回合开始后❺这个时机, 最近新杀滕芳兰能够在回合开始后❷-❹中某个时机弃牌, 我想到时候在用这个进行一遍测试.

**Comment by lolisix** [comment]
&emsp;&emsp;关于各个阶段开始前这个时机点, 我也做了类似的测试.
按照规则集的描述, 这些时机点不属于对应的阶段内.
![2023-03-31_124601.png](https://s2.loli.net/2023/03/31/o4B6xcFpdgWPfGM.png)
&emsp;&emsp;但是无名杀里面的结算方式是:
&emsp;&阶段回合内或回合外相关的描述), 且此次技能的发动次数计入到下一个没有被跳过的阶段.

**Comment by Spmario233** [comment]
代码跑的起来就行.jpg
细节什么的不重要啦 这坨屎山已经很难进行修改了
