### ISSUE TITLE
【bug】张任（非国战）穿心移除武将牌上的技能后，大小乔失去落雁却依然拥有天香和流离

### ISSUE THREAD

**Issue by Natsukage** [libccy/noname#1101]
和蹈节等技能的移除技能效果不同，张任的穿心仅仅只是让技能变灰，类似于被铁骑封印。
但是如果我没理解错的话，实际上张任的效果应该是完全移除原本技能。

如图所示，大小乔的武将牌上2个技能均已被张任移除。但是技能仅仅只是失效而并未被移除，已经被叠上去的舞也并没有被取除。
并且大小乔依然处于拥有天香和流离的状态，且可以正常发动流离

![f4a54b5db32e0bf180e95be85b5b31f1](https://github.com/libccy/noname/assets/19678081/97ee2c94-0a87-4935-bf84-5c29396fcd2e)
![94dd103a5b26672bd42910ae23154d49](https://github.com/libccy/noname/assets/19678081/5158f314-b128-45e5-909a-ab3ae2af62ca)

**Comment by Natsukage** [comment]
图中可能看不太清，因为开了HDR所以截出来的图有点白，但是星舞和落雁都是灰色的状态，和上面武将名的白字是有区别的

**Comment by Spmario233** [comment]
已修复
