### ISSUE TITLE
game.getFileList函数无法加载

### ISSUE THREAD

**Issue by Console2015** [libccy/noname#111]
浏览器:Microsoft Edge和Google
你回复我说是我添加的“手杀UI”扩展有问题,现在我换成“coin”扩展，我只在下注的代码里添加了该函数，同样提示:no function
coin.js line 85
`if(!game.phaseNumber&&!game.online){
	uiintro.add('下注');
	uiintro.add('<div class="coin_buy">本局获胜<div class="menubutton">20金</span></div></div>');
	var bet=uiintro.content.lastChild.lastChild.lastChild;
	bet.listen(function(){
		if(_status.betWin) return;
		_status.betWin=true;
		game.changeCoin(-20);
		this.innerHTML = '已下注';
		game.getFileList('extension/coin', function (floders) {
			var total = floders.length;
			alert(total);
		});
	});
	if(_status.betWin){
		bet.innerHTML='已下注';
	}
}`

**Comment by Console2015** [comment]
你要是还认为扩展有问题，这次我把所有的扩展全部关闭。
只允许GitHub下载的项目。
这次我在game.js line 46296 显示身份函数添加game.getFileList调用
ui.playerids=ui.create.system('显示身份',function(){
	if(game.showIdentity){
		game.showIdentity();
		_status.identityShown=true;
	}
	game.getFileList('extension/coin', function (floders) {
		var total = floders.length;
	       alert(total);
	});
},true);

**Comment by Console2015** [comment]
![coin](https://user-images.githubusercontent.com/32294598/229126172-b16878f4-a054-4e24-84bf-22000d667218.jpg)
![gameelseif](https://user-images.githubusercontent.com/32294598/229126176-ae5b0e2d-6c6e-492d-a37c-83da6e04818a.jpg)
![gameif](https://user-images.githubusercontent.com/32294598/229126181-bf839336-e99c-4b53-bcdb-3363cd8c4c6f.jpg)
两张图片是game.js初始化的调试结果，一张是coin扩展点击下注的调试结果。
**这还是扩展导致的问题？**

**Comment by Console2015** [comment]
你若不信，你可以在game.js初始化结束后的某个函数中，添加game.getFileList的调用。

**Comment by Spmario233** [comment]
早说你是浏览器环境啊
这些文件读写函数本身就是依赖Cordova或者Electron实现的 纯用浏览器没办法调用的
