### ISSUE TITLE
由于神张飞的存在, 在无名杀里, 无颜色算一种颜色吗? 无花色算一种花色吗? 及与此相关的bug.

### ISSUE THREAD

**Issue by lolisix** [libccy/noname#113]
&emsp;&emsp;由于神张飞的存在, 在无名杀里, 无花色算一种花色吗? 
&emsp;&emsp;神张飞-张嫙能够通过无色牌同礼, 说明无花色算一种花色, 荀攸奇策出其不意并对神张飞使用, 展示其无色牌, 荀攸不对神张飞造成伤害, 也能说明无色牌算一种花色.
但是TW神吕蒙攻心神张飞, 弃置其无色牌, 使其手牌中花色数减少, 又无法触发接下来的触发型效果, 这又说明无花色不是一种花色. 同理, 谋黄忠使用无色牌(包括与神张飞组成双将, 使用丈八蛇矛)不被记录花色, 也说明无色牌不是一种花色.

&emsp;&emsp;在无名杀里, 无颜色算一种颜色吗? 
&emsp;&emsp;我以前测试过, 无颜色牌可以触发观微, 这说明无颜色是一种颜色; 但是, 如果无色牌是一种颜色, TW神吕蒙为什么又不能攻心"令其不能使用或打出无色牌"?

&emsp;&emsp;我个人认为神张飞的无色牌属于极其危险的设计. 上面这些矛盾你肯定会修复的, 但是到底以哪个为基准, 我偏向与以「无花色不是一种花色」、与「无颜色不是一种颜色」为基准 (如果这样的话, 可以这样处理涉及到与颜色或是花色为字样的效果: 终止此结算, 于是后续效果无法被执行. 比如火攻神张飞, 神张飞展示无色牌, 则终止此结算, 于是后续效果无法被执行. 再比如出其不意神张飞, 神张飞展示无色牌, 则终止此结算. ). 当然, 实际结算还是你来决定.

&emsp;&emsp;另外, 与无颜色相关的结算有bug.
TW马岱-神张飞通过弃置无色牌潜袭玩家A, 玩家A在自己的回合, 不仅无法使用红色牌与黑色牌, 也无法通过丈八蛇矛使用无色牌.
谋黄忠的烈弓记录的四种颜色, 对神赵云使用杀并发动烈弓, 神赵云无法使用两张梅花闪(无色牌)相应.

**Comment by Spmario233** [comment]
这个事情官方都说不明白 无名杀就只能让它跑起来就行了
