### ISSUE TITLE
一些武将技能的发动时机有问题, 神张角的技能描述可能有问题.

### ISSUE THREAD

**Issue by lolisix** [libccy/noname#116]
&emsp;&emsp;一些武将技能的描述中的发动时机有问题, 如下:
* 神甘宁的劫营|drlt_jieying的获得标记的时机应为**准备阶段开始时**, 而不是回合开始时, 因为这个技能与飞扬同时机, 也就是神甘宁当地主时需要选择发动哪一个技能.
* 蔡夫人的窃听|qieting的正确时机为**回合结束时**, 不是结束阶段, 这是因为此技能的发动时机要比台湾神吕蒙的涉猎要晚.
* 界张颌的巧变|reqiaobian的跳过阶段的时机应为**某某阶段开始前(Before)**, 而不是某某阶段开始时(Begin).
*廖化|liaohua与界廖化|re_liaohua的当先的发动时机都应该是**回合开始时**, 而不是准备阶段.

上面那些问题我猜应该是由于以前的无名杀对时机划分不严格, 导致结束阶段与回合结束时为同一时机, 准备阶段与回合开始时为同一时机导致的.

* 还有一个武将台湾刘宏, 他的鬻爵①的发动时机应该是**其他角色的出牌阶段**, 而不是其他角色的出牌阶段内, 这个应该是我之前改描述时误改的.
----
下面还有一些武将的技能的描述有问题.
* 杜夫人的异色提供的延迟型效果应该是 其**下次受到因执行[杀]而造成的伤害时,此伤害+1**, 而不是受到杀的伤害, 因为无法通过连环伤害触发异色.
* 通过某种方式, 使得闪电被置入神张角的判定区, 在此牌因判定而置入弃牌堆后, 卢弈不可以通过复学拿到手牌区, 说明执行延迟型锦囊牌的特殊使用流程算使用此牌, 但是神张角若被此闪电劈中, 三首亮出三张锦囊牌, 此伤害会被防止, 这又说明此时闪电不算被使用, 这产生了矛盾. 所以我认为应该修改神张角的描述: 若其中有本回合**未被非系统使用过**的牌的类型,防止此伤害.
* 璀璨星河的董白|dongbai的黠慧|xiehui提供的状态型效果是持续到"减少体力", 但是由于减少体力上限而减少体力不会使此状态型效果消失, 所以这里应该改成: 其不能使用、打出、弃置这些牌直到其体力值**扣减**为止.
----

**Comment by lolisix** [comment]
韩猛的劝酒技能描述有问题, 原描述为:
劝酒: 锁定技②你使用对应的实体牌为一张[酒]的**非转化**[杀]不计入次数限制.
正确描述应该是
劝酒: 锁定技②你使用对应的实体牌为一张[酒]的**转化**[杀]不计入次数限制.

**Comment by Spmario233** [comment]
其中确认为bug的部分下个版本修。
另外界张郃【巧变】的时机是正确的。只有结束阶段获得标记的时机是phaseJieshuBegin，其他的都是xxxBefore。
