### ISSUE TITLE
无名杀中是如何仅从描述上判断一个技能的延迟型效果能否叠加?

### ISSUE THREAD

**Issue by lolisix** [libccy/noname#118]
&emsp;&emsp;无名杀中是如何仅从描述上判断一个技能的延迟型效果能否叠加? 在规则集中, 我没有找到任何依据规定延迟型效果能够叠加或是不能够叠加. 在规则集中, 只能找到技能不能叠加的依据.
![](https://s2.loli.net/2023/05/05/zNAJW41U5jHBYxq.png)
&emsp;&emsp;但是我偏向于这个效果不能叠加, 理由如下: 如果界鲁肃同一回合执行两次好施并把牌都交给同一名玩家A, 那么当本回合界鲁肃使用无中生有时, A应该执行两次同一个效果{交给界鲁肃一张牌}, 还是执行一次效果{交给界鲁肃两张牌}, 还是执行一次效果{交给界鲁肃一张牌}? 我认为最后一种情况更为合理. 
&emsp;&emsp;若是如此, 在不修改描述的情况下, 徐褚在一回合双裸衣, 造成的伤害只加1, 关羽在一回合双义绝, 造成的伤害也只加1.
&emsp;&emsp;若是如此, 有如下几个武将描述需要修改: 杜夫人的异色、刘繇的戡难.
&emsp;&emsp;还有一个武将描述与代码可能都需要修改, 是张让. 张让的滔乱提供的延迟型效果连续执行两个效果{失去1点体力}, 这个应该修改为执行一个效果{失去2点体力}.

**Comment by Spmario233** [comment]
答案是和官方一样 纯看心情
官方在很多地方的结算也都是一团糊涂账。
