### ISSUE TITLE
版本v1.10.10 更新地址有误

### ISSUE THREAD

**Issue by welf0627** [libccy/noname#1196]
版本v1.10.10
那个素材包没法更新，解决一下？或者有没有好心人把它上传到百度网盘给个链接？谢谢！

**Comment by 1937475624** [comment]
等1.10.11吧1.10.11更改了更新机制应该能解决问题

**Comment by welf0627** [comment]
> 等1.10.11吧1.10.11更改了更新机制应该能解决问题

好的，谢谢！
