### ISSUE TITLE
使用反向代理有子路径时，serviceWorker的scope错误

### ISSUE THREAD

**Issue by ICE-GB** [libccy/noname#1247]
## 问题描述
使用反向代理有子路径时，serviceWorker的scope错误

## 问题信息

示例路径：`http://a.b.com/noname`

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by nonameShijian** [comment]
目前如果网页的路径不是以/结尾，而是以/index.html或者/app.html类似的文件名作为结尾时这个也会失效，要不你也尝试修一下
