### ISSUE TITLE
文件读写函数添加一个检查文件是否存在的方法

### ISSUE THREAD

**Issue by ICE-GB** [libccy/noname#1250]
## 功能描述
目前许多扩展都依赖于某些文件是否存在进行下一步逻辑判断，但是通常都是自己手动写了一个方法，只有node环境或者cordova环境可用，希望本体能提供一个检查文件是否存在的方法，便于提升扩展对不同平台的兼容性

### 使用的环境、平台、设备

浏览器访问nginx代理的无名杀，自行提供`/readFile`等接口来实现文件读写函数，由于缺少检查文件是否存在方法，改动拓展相关代码比较麻烦

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by nonameShijian** [comment]
在有game.readFile的情况下，你可以使用new promise 里面写game.promises.readFile().then(reject).catch(resolve)来实现判断是否有文件的判断。文件夹另说

**Comment by ICE-GB** [comment]
> 在有game.readFile的情况下，你可以使用new promise 里面写game.promises.readFile().then(reject).catch(resolve)来实现判断是否有文件的判断。文件夹另说

请问这个方法不会实际下载文件吗？

**Comment by nonameShijian** [comment]
> > 在有game.readFile的情况下，你可以使用new promise 里面写game.promises.readFile().then(reject).catch(resolve)来实现判断是否有文件的判断。文件夹另说
> 
> 请问这个方法不会实际下载文件吗？在浏览器环境下，index.html里面的调用接口的情况下

不是只有直接url访问文件然后后端设置下载的字段才能是下载吗？实际上我写的readFile接口只是返回byte[]而已，然后网页自己处理成ArrayBuffer

**Comment by ICE-GB** [comment]
> > > 在有game.readFile的情况下，你可以使用new promise 里面写game.promises.readFile().then(reject).catch(resolve)来实现判断是否有文件的判断。文件夹另说
> > 
> > 
> > 请问这个方法不会实际下载文件吗？在浏览器环境下，index.html里面的调用接口的情况下
> 
> 不是只有直接url访问文件然后后端设置下载的字段才能是下载吗？实际上我写的readFile接口只是返回byte[]而已，然后网页自己处理成ArrayBuffer

不好意思，我那个下载的意思就是已经返回了byte[]，服务器带宽不足时，当判断比较大的文件时，会占用一部分带宽，这个流量还是能少就少，目的只是想知道文件或者文件夹是否存在，并不想实际拿到文件内容

**Comment by ICE-GB** [comment]
还有个感觉就是刷新页面时，好像所有资源文件都会重新下载，浏览器开发者工具没有看到磁盘缓存的标识，这个不知道是我操作有误还是就是这样的，总之就是想尽量减少流量，提升速度

**Comment by nonameShijian** [comment]
那只能是自己新写个api了
