### ISSUE TITLE
神诸葛技能结算问题

### ISSUE THREAD

**Issue by DUXING130** [libccy/noname#1260]
## 错误信息

神诸葛亮在出牌阶段结束后显示必须发动技能，没有取消
![image](https://github.com/libccy/noname/assets/95281874/bdfc9824-55cb-4841-b3c0-d493fb324ff3)
### 使用的环境、平台、设备

Windows

### 版本信息

Windows64，1.10.11.3

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x ] 我已将所有扩展更新为最新版本
- [x ] 我填写了上面所有必要的信息

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by xiaoas** [comment]
选择狂风 -> 选择取消 -> 选择取消

**Comment by Spmario233** [comment]
随便点进去一个 再点取消
