### ISSUE TITLE
更新后扩展出现错误

### ISSUE THREAD

**Issue by Grady4869** [libccy/noname#1264]
更新最新版本后我的千幻聆音扩展崩了
![Screenshot_2024-04-23-15-37-14-035_com noname xuanwu](https://github.com/libccy/noname/assets/167890596/4c3cb126-0587-48d3-ab6d-f9559dc22ab4)
如图

**Comment by universe-st** [comment]
千幻聆音崩了你提universe_st/qianhuan去，提这里干什么？而且你这千幻是老版本了啊，得去下新的啊。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月23日(周二) 晚上10:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [libccy/noname] 更新后扩展出现错误 (Issue #1264)




 
更新最新版本后我的千幻聆音扩展崩了
 Screenshot_2024-04-23-15-37-14-035_com.noname.xuanwu.jpg (view on web)
 如图

**Comment by Grady4869** [comment]
主要是新的扩展一直导入不了
![Screenshot_2024-04-23-15-37-24-100_com noname xuanwu](https://github.com/libccy/noname/assets/167890596/b09d099d-8ef5-4d33-9da0-e93271716dcc)

**Comment by universe-st** [comment]
无名杀本体升级到1.10.11.3，外壳用诗笺版。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月24日(周三) 凌晨0:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [libccy/noname] 更新后扩展出现错误 (Issue #1264)




 
主要是新的扩展一直导入不了
 Screenshot_2024-04-23-15-37-24-100_com.noname.xuanwu.jpg (view on web)
