### ISSUE TITLE
新SP关羽觉醒异常

### ISSUE THREAD

**Issue by geversite** [libccy/noname#1271]
## 错误信息

斗地主模式，三号位，地主黄皓，二号位魏小鸟。关羽三血四牌。（我测试似乎斗地主任何条件下觉醒都会出现卡住的问题）卡住了，表现为无法操作牌，没有按钮，体力上限被减一
而且每次刷新（我不知道应不应该这么叫）都会减一点上限，比如我长按卡片显示描述的时候，最后我体力上限扣完死了，游戏仍没有继续进行

### 使用的命令或代码

无

### 使用的环境、平台、设备

安卓，1.6.0
1.10.8完整包

### 版本信息

安卓，其他版本没测

## 检查清单

- [ ] 此问题没有在其他issue(议题)中出现
- [ ] 我已将无名杀本体更新为最新版本
- [ ] 我已将所有扩展更新为最新版本
- [ ] 我填写了上面所有必要的信息

**Comment by Spmario233** [comment]
你的版本疑似有点旧了
