### ISSUE TITLE
bug:sp貂蝉可以响应承包邹氏翻面摸牌

### ISSUE THREAD

**Issue by TruthCat** [libccy/noname#1281]
## 错误描述
bug:sp貂蝉可以响应承包邹氏翻面摸牌
## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [ ] 我填写了上面所有必要的信息

**Comment by TruthCat** [comment]
![截图](https://github.com/libccy/noname/assets/39005143/911b0069-49bd-42a3-8e63-81438cb93af1)

**Comment by Spmario233** [comment]
这个结算没有问题。
女性角色只是不能靠响应〖孤吟〗进行翻面而已。如果本身已经因为其他原因翻面，是可以摸牌的。
