### ISSUE TITLE
吴兰技能挫锐时，如果对方手牌装备都没有对应颜色的牌，结算就会卡住，如图。

### ISSUE THREAD

**Issue by TruthCat** [libccy/noname#1310]
![2](https://github.com/libccy/noname/assets/39005143/1bff9ef5-a92a-47d8-bb12-fd7604fc4ec1)
### 使用的环境、平台、设备

PC

### 版本信息
win64

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by TruthCat** [comment]
准确的说是对方没有手牌可展示，也没有对应颜色的准备。

**Comment by Spmario233** [comment]
已在开发分支修复
