### ISSUE TITLE
国战双将位置与卡牌显示出错

### ISSUE THREAD

**Issue by xushanthu-2014** [libccy/noname#1330]
我现在在Mac chrome上运行https://adefulodgu.github.io/noname/。但是在国战模式中，前几天的双将摆位还是左右，现在突然变成了上下。同时卡牌显示也发生了变化。具体见下图：
![Screenshot 2024-05-08 at 21 41 33](https://github.com/libccy/noname/assets/60925333/8d0f1b28-703c-4ac4-9be5-454887f0d43c)

**Comment by Spmario233** [comment]
改一下布局就行

**Comment by xushanthu-2014** [comment]
咋改布局？没看到可以改这个的。。。
