### ISSUE TITLE
更新的按钮没有了

### ISSUE THREAD

**Issue by bobo1key** [libccy/noname#1335]
## 问题描述
![屏幕截图 2024-05-10 172309](https://github.com/libccy/noname/assets/58775729/52280cb2-c898-4a74-9835-6d8e03e6fbcb)
## 问题信息

想要更新素材却发现没有更新按钮
### 版本信息
win64

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by Spmario233** [comment]
你这是网页版罢
