### ISSUE TITLE
制作和修改本地扩展失效

### ISSUE THREAD

**Issue by XyH-chase** [libccy/noname#1346]
## 问题描述
电脑端的无名杀，用“制作扩展”之后保存，不显示，而且对应文件夹里只有一个空的LICENSE文件，没有extension.js.

## 问题信息

server.exe启动的网页版，使用【制造扩展】或对自己的扩展进行修改后，点击”保存“，并点击出现的”保存成果，重新启动“后，自己的扩展不能显示，点开extension文件夹，发现只有一个空的LICENSE文件，没有extension.js

### 使用的命令或代码

随便创建一个扩展，保存后消失。不显示在UI里，而且点进文件夹只有一个空的LICENSE文件，没有extension.js

### 使用的环境、平台、设备

电脑端，使用server.exe打开的网页版。

### 版本信息

下载的noname-1.10.12全文件，windows系统。

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by fmk54330502** [comment]
遇到了同样的问题，客户端使用正常。在extension文件夹中删除文件、或通过客户端生成新的扩展后，客户端可以正常识别这些增删，通过网页则仍然会显示默认的4个扩展。

**Comment by fmk54330502** [comment]
补充：保存扩展时发现服务器窗口提示Entity too large。在网页端清除IndexedDB数据后，可以正常保存扩展，但估计数据量大之后仍然会有问题？

**Comment by nonameShijian** [comment]
> 补充：保存扩展时发现服务器窗口提示Entity too large。在网页端清除IndexedDB数据后，可以正常保存扩展，但估计数据量大之后仍然会有问题？

你应该更新noname-server.exe了

**Comment by XyH-chase** [comment]
> 网页版默认用的indexdb存储扩展文件的写法还没改
> 
> @Rintim @kuangshen04

请问现在有办法解决吗？好像电脑端只有server.exe版本的

**Comment by fmk54330502** [comment]
> > 网页版默认用的indexdb存储扩展文件的写法还没改
> > @Rintim @kuangshen04
> 
> 请问现在有办法解决吗？好像电脑端只有server.exe版本的

电脑端有客户端版本的，直接读取extensions文件夹下面的内容，可以用

**Comment by XyH-chase** [comment]
> > > 网页版默认用的indexdb存储扩展文件的写法还没改
> > > @Rintim @kuangshen04
> > 
> > 
> > 请问现在有办法解决吗？好像电脑端只有server.exe版本的
> 
> 电脑端有客户端版本的，直接读取extensions文件夹下面的内容，可以用

呃，请问这个在哪里啊，我没看到有其它的exe文件

**Comment by fmk54330502** [comment]
> > > > 网页版默认用的indexdb存储扩展文件的写法还没改
> > > > @Rintim @kuangshen04
> > > 
> > > 
> > > 请问现在有办法解决吗？好像电脑端只有server.exe版本的
> > 
> > 电脑端有客户端版本的，直接读取extensions文件夹下面的内容，可以用
> 
> 呃，请问这个在哪里啊，我没看到有其它的exe文件

https://github.com/libccy/noname/releases/tag/chromium77-client在这里下载客户端
