### ISSUE TITLE
关于十周年周宣的代码问题zhouxuān

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [libccy/noname#136]
周宣的代码的名字为啥要用dc_zhouxuān来写呢？

**Comment by Spmario233** [comment]
因为有名叫“周旋”的技能 可能会和周宣产生冲突

**Comment by S-N-O-R-L-A-X** [comment]
> 因为有名叫“周旋”的技能 可能会和周宣产生冲突

但是其他技能也有重名的吧？好像之前都是只加前缀，没见过用拼音的操作？
