### ISSUE TITLE
天牢与将池的问题

### ISSUE THREAD

**Issue by casdfa** [libccy/noname#1361]
能否在下次版本更新中优化：
## 功能描述
天牢与将池的问题。
无名杀目前只有一个禁将功能，但这个功能，会影响到将池的选将，比如，许劭，赵襄，现在新版本的吴懿等等。
一些武将是无法正常对局的，比如张飞，郭嘉，但将池技能又非常需要这两个技能，这就导致，想要好的体验，那就要舍弃掉许劭这种依赖将池的武将。

我在想是否可以用以下内容解决，选将将池是独立开的，天牢关的是选将将池，但不会影响到技能的调用。

我不是很懂代码，不清楚里面的复杂程度。

## 功能信息
无

### 使用的环境、平台、设备
windows

### 版本信息
最新
您正在使用哪些相关版本？
win64位

## 检查清单

- [ x] 此问题没有在其他issue(议题)中出现
- [ x] 我已将无名杀本体更新为最新版本
- [ x] 我已将所有扩展更新为最新版本
- [ x] 我填写了上面所有必要的信息

**Comment by casdfa** [comment]
如不方便优化，也请给我一回复

**Comment by Spmario233** [comment]
暂时没有调整的计划。
