### ISSUE TITLE
起刘备在AI代选弃牌时会报错

### ISSUE THREAD

**Issue by Mr-Chunjie** [libccy/noname#1390]
## 错误描述
起刘备在AI代选弃牌时会报错
## 错误信息

![image](https://github.com/libccy/noname/assets/43920577/1c06ce9e-995d-42f3-bb7d-ec2556acdc43)

### 使用的命令或代码

斗地主模式选择起刘备AI代选弃牌
### 使用的环境、平台、设备

win64

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by YouXiShiJie** [comment]
我托管起刘备弃牌也遇到报错

**Comment by Xiazhiliao** [comment]
![@O7H L54`UOJ ZF6WASLRJA](https://github.com/libccy/noname/assets/164357750/2c9d9c71-4dae-4b34-9c9b-62c78bd0708a)
参数丢失了，得往aiUseful的括号里头输入card,player,num三个参数，而且用箭头语法糖会报错，得改成function形式或者调用已有的方法
![QQ图片20240528151949](https://github.com/libccy/noname/assets/164357750/ec4b2356-aac1-4717-a275-01d0b2c233ac)
