### ISSUE TITLE
关于中流中重置技能上的疑问, 我感觉下面的结算应该是bug.

### ISSUE THREAD

**Issue by lolisix** [libccy/noname#1486]
## 问题描述
中流的描述是「你重置武将牌上的技能」, 按照我对重置的理解, 应该是把技能恢复到某个时间点的状态, 但是这个重置似乎只能重置限定技、「出牌阶段限X次」、「每轮限X次」等类型的技能. 这里X是一个定值, 不是变量.

> 滔乱: 你可将一张牌当做任意一张基本牌或普通锦囊牌使用(此牌不得是本局游戏你以此法使用过的牌,且每回合每种花色限一次)......

1. 新杀张让(四花色张让)用红桃牌滔乱趁火打劫, 然后想办法触发一次中流, 此时即无法再通过滔乱使用红桃牌转换牌, 也没法通过滔乱去使用趁火打劫. 其中红桃牌是每回合限一次, 趁火打劫是每局限一次. 我认为此结算是bug.

2. 新杀张让因滔乱使用牌后, 滔乱被失效了, 然后想办法触发一次中流, 此时滔乱仍然处于失效状态. 本回合开始时, 滔乱是非失效状态, 不确定中流的重置技能应不应该让滔乱再生效.

>力激: 出牌阶段限X次......(X为本回合内进入过弃牌堆的卡牌数除以4,向下取整)

3. 新杀留赞首先先想办法让本回合有11张牌进入过弃牌堆, 再把3次本身自带的力激使用掉((11+3)÷4=3余2), 然后想办法通过中流来重置技能, 然后依然没有力激的发动次数, 此时再想办法让2张牌进入弃牌堆, 又能够发动且仅发动一次力激. 虽说这里的技能的发动次数不是一个定值, 但是按「重置」这两个字理解, 我认为应该能够再使用3次力激, 也就是我认为此结算是bug.

>解悬: 限定技,转换技.阴.......阳......
>抚宁: 当你使用牌时......然后弃置X张牌(X为你本回合内发动过〖抚宁〗的次数).

4. 另外, 中流这个技能的描述确实不能是「此技能未发动过」, 因为如果是技能一直没有发动过, 族王允的解悬应当始终处于阴状态. 虽然我还没去试, 但是如果新杀赵俨发动几次抚宁, 然后想办法触发中流, 那么抚宁中的X应该不会被调整为0.

5. 如果让我来改中流的描述, 那么我认为应该是「你将武将牌上的技能的发动次数重置」. 如此一来, 对于问题1., 只能通过滔乱转换至多4张牌就不是bug(即使用中流重置过), 因为滔乱最多只能转换4张牌是因为只有4种花色, 而不是此技能只能发动4次. 对于问题2, 也不是bug, 因为再怎么样重置技能的发动次数, 失效的技能就是无法被触发. 这种描述也不会破坏问题4的结算, 因为技能确实发动过, 只不过能再发动几次. 在这种描述下, 唯一有问题的只有问题3.

6. 其中关于中流还有一个描述错误, 首先, 曹爽不是王家的人, 但是曹爽获得中流, 再使用一张手牌后, 没有触发中流的语音(没测试过技能是否被重置, 但是如果触发了技能的后续效果, 那么应该会触发一次语音.), 由于曹爽不是王家的人, 那么他的手牌自然不是太原王氏的角色的手牌, 那么应该会触发中流, 然后触发语音. 这说明技能中还隐藏了「你的手牌」.

7. 综上, 我认为中流的描述应该改为: 「宗族技,锁定技.当你使用牌时,若此牌对应的实体牌均不为太原王氏角色**或你**的手牌,你重置武将牌上的技能**的发动次数**」.

### 使用的命令或代码
不需要特殊命令或代码

### 使用的环境、平台、设备
应该和平台无关, 我使用的是win10.

### 版本信息
应该也和启动器版本无关, 我使用的是win10-32x , 应该是诗筏版1.6.1.

## 检查清单

- [x ] 此问题没有在其他issue(议题)中出现
- [ x] 我已将无名杀本体更新为最新版本
- [x ] 我已将所有扩展更新为最新版本 , 我没有使用扩展
- [ x] 我填写了上面所有必要的信息

**Comment by AstralBarrage** [comment]
留赞的原描述是“出牌阶段限零次”，所以某种意义上不能重置是正确的（
中流的描述问题主要在于原版描述就是和实际效果不符的，而且不能跨服测试一些特殊情况搞不到正确结算，只能村规了
至于问题6的话是因为无名杀要考虑双将族王做副将的情况，所以处理上如果你持有中流，你使用自己的手牌也会视为使用的同族角色手牌，不然副将族王用一张重置一次全是永动机

**Comment by Spmario233** [comment]
这东西跑起来是什么样就是什么样
