### ISSUE TITLE
bug：托管后卡死

### ISSUE THREAD

**Issue by lieren2023** [libccy/noname#1514]
## 错误描述
托管后卡死：包括hearth.js的jinhua等技能、diy.js的nsbaiming技能、gwent.js的gwfengchi技能

## 错误信息

无报错信息

（可能）有问题的代码，因为注释掉`game.resume();`后不卡死了（不知道是不是这么修）
```
event.switchToAuto = function () {
	event._result = event.skillai();
	dialog.close();
	game.resume();
};
```

### 使用的命令或代码

无

### 使用的环境、平台、设备

所有平台

### 版本信息

初步测试后发现，1.10.1.0.1后的某一版本开始就有此问题了

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by IceCola97** [comment]
game.resume没了反而不卡死了喵？奇怪哦
