### ISSUE TITLE
黄承彦发动解阵游戏卡死

### ISSUE THREAD

**Issue by lanmeie** [libccy/noname#1528]
黄承彦发动解阵游戏卡死

**Comment by lzy2225846500** [comment]
问一下这种卡死是报错的那种卡死吗，还是没有反应，点击都没有反应。

**Comment by lanmeie** [comment]
> 问一下卡死是报错的那种卡死吗，还是没有报错直接不动，点击都没用？
没有报错，直接都不动了，托管也没用，只能重启才行

**Comment by lanmeie** [comment]
> 问一下卡死是报错的那种卡死吗，还是没有报错直接不动，点击都没用？

没有报错，直接都不动了，托管也没用，只能重启才行

**Comment by QCXYLTJ** [comment]
我不信，你肯定开了兼容模式，要不就是安装了某个取消弹窗的扩展

**Comment by lanmeie** [comment]
> 我不信，你肯定开了兼容模式，要不就是安装了某个取消弹窗的扩展

好的，我重装一个没有扩展的试一下，我记得之前把东西全关了来着，可能是兼容模式没关掉

**Comment by lanmeie** [comment]
> 我不信，你肯定开了兼容模式，要不就是安装了某个取消弹窗的扩展

发现了，开了流畅模式，导致没有报错

**Comment by lanmeie** [comment]
![QQ截图20240701154936](https://github.com/libccy/noname/assets/173601463/b4896ccb-045a-4dad-b952-1154841dbb09)

**Comment by Rintim** [comment]
这个BUG已在 #1508 中得到了修复
