### ISSUE TITLE
setting window.ai

### ISSUE THREAD

**Issue by dataf3l** [libccy/noname#1533]
https://github.com/libccy/noname/blob/571c90385e853d4837c44dbfd05431894b1bc87d/noname/ai/index.js#L18

so this "var ai=" thing  or using window.ai or setting this value, may have a problem with upcoming changes on the chrome browser and possibly also nodejs as it usually mimics browser apis precisely, as it hides window.ai maybe it should be renamed to prevent future potential conflicts to another name.

this is just speculation. but I think maybe google will want window.ai for itself.
so this code may break when interacting with other code in the future perhaps.
specially if done globally.

see this link for details.
https://developer.chrome.com/docs/ai/built-in

right now it's behind a flag but in the future this may change.

not clear on the timeline tho.

have an awesome day!

**Comment by Spmario233** [comment]
ok
