### ISSUE TITLE
星孙坚【锐军】多目标牌结算错误

### ISSUE THREAD

**Issue by wxsthuee** [libccy/noname#1611]
## 错误信息
【锐军】的效果理应是选择其中一名目标执行，但是结算时可以选择一名目标X次，X为使用牌指定的目标数。

### 使用的环境、平台、设备
macOS，1.10.14

### 版本信息
macOS

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by Spmario233** [comment]
已修复
