### ISSUE TITLE
星孙尚香【骄豪】错误

### ISSUE THREAD

**Issue by wxsthuee** [libccy/noname#1612]
## 错误信息
无法使用拼点牌。
cards.filterInD("d")之后为空。

### 使用的环境、平台、设备
macOS，1.10.14

### 版本信息
macOS

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by Spmario233** [comment]
未成功复现。
