### ISSUE TITLE
建议修改本体图片素材的格式

### ISSUE THREAD

**Issue by dragonJadeRan** [libccy/noname#1616]
## 功能描述
将所有jpg,png改为webp的格式以减少空间的占用并提升项目的性能,并且不用再区分 png或者jpg的后缀
将mp3格式的音频素材换成opus
## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by Spmario233** [comment]
祖宗之法不可变
而且有沟槽的iOS
