### ISSUE TITLE
nogain查无方法

### ISSUE THREAD

**Issue by TianyaSKY** [libccy/noname#1632]
## 错误描述
打开游戏刷完手气卡后直接报错
## 错误信息

更新了最新版本后产生
### 使用的环境、平台、设备

win64

## 检查清单

- [ ] 此问题没有在其他issue(议题)中出现
- [ ] 我已将无名杀本体更新为最新版本
- [ ] 我已将所有扩展更新为最新版本
- [ ] 我填写了上面所有必要的信息
- [ ] 
![image](https://github.com/user-attachments/assets/e9e36898-e572-46b1-ae91-85fa95747b56)

**Comment by Spmario233** [comment]
![图片](https://github.com/user-attachments/assets/001bda54-4746-4aa5-a557-66e18eeea3d5)
无名杀本体是没有“gainTo”这个关键字的。这是一个来自于十周年UI的覆盖代码。请卸载十周年UI。

**Comment by happybub** [comment]
如果还无法解决的话，请尝试修改十周年UI拓展包中的`extension.js`文件，在文件中搜索:
`/(?=\s*if\s*\(\s*event\s*\.\s*animate\s*==\s*'draw'\s*\)\s*{)/`
替换为
`/(?=\s*if\s*\(\s*event\s*\.\s*animate\s*==\s*['"]draw['"]\s*\)\s*{)/`
即可解决问题。

具体问题原因，这里的`extension.js`通过replace函数进行正则匹配，动态地修改了`lib.element.content.gain`函数，在满足:
```
if (event.animate == 'draw') {
    // some code here...
}
```
格式的代码后注入`gainTo`函数的定义，但是此处应当匹配双引号而非单引号，因此修改replace时使用的正则表达式即可成功注入。
