### ISSUE TITLE
保存拓展时出现bug

### ISSUE THREAD

**Issue by TianyaSKY** [libccy/noname#1642]
## 错误描述
自制拓展保存后，文件格式会出现错误
## 错误信息

例如filter:function()会变成filter:filter()
order:function() => order:order()
### 使用的命令或代码

保存
### 使用的环境、平台、设备

win64 1.10.14

### 版本信息

win64

## 检查清单

- [ ] 此问题没有在其他issue(议题)中出现
- [ ] 我已将无名杀本体更新为最新版本
- [ ] 我已将所有扩展更新为最新版本
- [ ] 我填写了上面所有必要的信息

**Comment by nonameShijian** [comment]
需要更具体的信息，是电脑还是手机，以及具体的哪个操作

**Comment by TianyaSKY** [comment]
![image](https://github.com/user-attachments/assets/1f0b2cbe-1853-4c9a-973a-2eaf733bd7e4)
![image](https://github.com/user-attachments/assets/bb3f6869-822c-4140-a9d2-2b2682e42852)
电脑按下保存键后重启如图所示

**Comment by TianyaSKY** [comment]
![image](https://github.com/user-attachments/assets/75b13429-1474-43b9-a52b-417b95e6c00c)

**Comment by TianyaSKY** [comment]
ok了
