### ISSUE TITLE
无名杀可以加欢乐杀武将吗

### ISSUE THREAD

**Issue by Michaellggit** [libccy/noname#1654]
## 问题信息
如题  
包括但不限于喵武将  
个人感觉欢乐杀有很多有意思的武将

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by TianyaSKY** [comment]
拓展活动武将

**Comment by xizifu** [comment]
目前不加，你可以去萌佬（@mengxinzxz）的活动武将扩展体验
