### ISSUE TITLE
bug：手杀曹髦清正技能有误

### ISSUE THREAD

**Issue by Michaellggit** [libccy/noname#1655]
## 错误信息
曹髦的清正现在版本为弃自己一种花色的牌而不是两种。
<https://wiki.biligame.com/msgs/%E6%9B%B9%E9%AB%A6>

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by xizifu** [comment]
现在就是弃置一种花色

**Comment by Michaellggit** [comment]
没事了
