### ISSUE TITLE
docker跑起来报错

### ISSUE THREAD

**Issue by CiyLei** [libccy/noname#1662]
## 问题描述
docker打包好，跑起来报错
![image](https://github.com/user-attachments/assets/8661b8e8-3249-4859-8e19-2c3e3dd87bab)

## 问题信息
node版本v18.20.4，我进到容器里面，node下跑 `import * as fs from "node:fs";` 也报错

### 使用的命令或代码
docker刚刚打包出来的

### 使用的环境、平台、设备
群辉docker

### 版本信息
群辉docker

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by Rintim** [comment]
非常感谢你的反馈，这个问题是因为：

- 无名杀仓库因历史原因不存在`package.json`文件，导致node.js在没配置的情况下只能以默认的`commonjs`模式读取模块，且nodejs无法同时使用`commonjs`和`ES Module`，故在`commonjs`中使用`ES Module`会出现报错
- 由于除node.js以外的其他Javascript运行时均采用了`ES Module`，故为了使大部分运行时都能运行（主要是deno.js，因为能直接import网络内容，我常用这个运行时编写脚本），故采用了`ES Module`的形式编写`noname-server.js`；且当时防止`ES Module`在ide报错，在本机上创建了`package.json`并修改配置使ide知道是`ES Module`项目，从而在本机测试时不会存在问题

很抱歉因为疏忽造成了bug，这个bug将在不久后得到修复
