### ISSUE TITLE
杨彪和杜夔受伤后不能移动延时类锦囊

### ISSUE THREAD

**Issue by wvevwawweba** [libccy/noname#1679]
## 错误描述
杨彪和杜夔受伤后不能移动延时类锦囊
## 错误信息

我控制杨彪受到一点伤害后将乐不思蜀移到自己，到了对面回合乐不思蜀居然还判定，没移过来。
![Screenshot_20240805_125429](https://github.com/user-attachments/assets/1bd35b32-640b-49de-8602-94a80221c050)
![Screenshot_20240805_125442](https://github.com/user-attachments/assets/89175d0f-43ae-40dd-9699-610d661b4c0c)

### 版本信息

win64,1.10.14

### ### - [ ] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by Rintim** [comment]
`moveCard`只将判定牌的`card`传给了`addJudge`，然而`addJudge`因为转向`addVirtualJudge`需要将实体牌也传入进去，这导致了移动判定牌将只有动画效果

该问题将在不久后修复，感谢你的反馈
