### ISSUE TITLE
Docker启动报错

### ISSUE THREAD

**Issue by Ishiki-Iroha** [libccy/noname#1721]
缺少ws模块，建议Dockerfile改为：
```
FROM node:18

WORKDIR /app

COPY ./docker/* ./

RUN npm config set registry https://registry.npmmirror.com/

RUN npm install body-parser express minimist ws

COPY . .

EXPOSE 8080
EXPOSE 8089

CMD [ "sh","./start.sh" ]
```

**Comment by Rintim** [comment]
在 #1668 中已经修复了没有ws的问题，请提issue前检查PR-Branch的相关代码，以免遗漏最新的更新

由于没有无名杀Docker群体的用户数据，个人不太确定Dockerfile中是否该直接使用淘宝镜像源

如果可以的话，请使用issue模板填写内容，以便更好的突出问题主体

**Comment by Ishiki-Iroha** [comment]
> 在 #1668 中已经修复了没有ws的问题，请提issue前检查PR-Branch的相关代码，以免遗漏最新的更新
> 
> 由于没有无名杀Docker群体的用户数据，个人不太确定Dockerfile中是否该直接使用淘宝镜像源
> 
> 如果可以的话，请使用issue模板填写内容，以便更好的突出问题主体

好的，非常抱歉
