### ISSUE TITLE
来自陈登的 bug

### ISSUE THREAD

**Issue by xiezheyuan** [libccy/noname#1770]
## 错误描述

陈登结算望族技能时会报错。

![image](https://github.com/user-attachments/assets/30c8460d-4e5e-4cb6-9d44-120667c331c6)

问题适用于所有版本，不知如何复现。

## 检查清单

- [ x ] 此问题没有在其他issue(议题)中出现
- [ x ] 我已将无名杀本体更新为最新版本
- [ x ] 我已将所有扩展更新为最新版本
- [ x ] 我填写了上面所有必要的信息

**Comment by xizifu** [comment]
这个bug已经修复很久了，现在是10.15.1了，可以更新至最新版本再来反馈bug
