### ISSUE TITLE
1.10.15扩展报错：this.content is not a function(gameEvent.js)

### ISSUE THREAD

**Issue by NanaharaShuya** [libccy/noname#1775]
## 错误描述
.14及以前可用的部分自制扩展技能在.15出错
## 错误信息

1.10.15错误图片
![image](https://github.com/user-attachments/assets/cf4ba116-2a5c-45f2-8659-890af6c4d709)
1.10.13正常运行图片
![image](https://github.com/user-attachments/assets/29bc4d12-785b-4124-a876-69a6ae4933d0)

### 使用的命令或代码

运行出错的代码示例，报错时机为该角色的准备阶段
```javascript
					skillname: {
						trigger: { player: ["phaseZhunbei", "phaseJieshu"] },
						filter(event, player) {
							return player.countCards("he") > 0;
						},
						direct: true,
						content(event, player) {
							player.draw();
						},
					},
```
另：将phaseZhunbei修改为phaseZhunbeiBegin仍出错，但报错时机会提前（gamelog中是否显示“(角色)进入了准备阶段”的区别）

另另：原先使用以下方式添加的分栏也失效了
```javascript
	lib.characterSort["mode_extension_" + ext.name] =
		ext.package.character.characterSort;
```

### 使用的环境、平台、设备

win11&Android
游戏环境未安装除该自制扩展外的任何扩展

### 版本信息

使用win64环境的1.6.4诗笺版，游戏版本为1.10.13/1.10.14/1.10.15

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by zhichaoxi2006** [comment]
请改成类似如下的样式：
```javascript
skillname: {
	trigger: { player: ["phaseZhunbei", "phaseJieshu"] },
	filter(event, player) {
		return player.countCards("he") > 0;
	},
	direct: true,
	content() {
		player.draw();
	},
},
``` 
形如`content(event, player){}`（即在step-content写法的function中填入参数）在1.10.15中被认为是**不被支持的content**，无法运行。

**Comment by NanaharaShuya** [comment]
> 请改成类似如下的样式：
> 
> ```js
> skillname: {
> 	trigger: { player: ["phaseZhunbei", "phaseJieshu"] },
> 	filter(event, player) {
> 		return player.countCards("he") > 0;
> 	},
> 	direct: true,
> 	content() {
> 		player.draw();
> 	},
> },
> ```
> 
> 形如`content(event, player){}`（即在step-content写法的function中填入参数）在1.10.15中被认为是**不受支持的content**，无法运行。

感谢。
另请问，content需要引用参数时，是采用content:function(*args)的形式吗？
另另请问，1.10.15中分栏(characterSort)是否也是变更了调用方式？
