### ISSUE TITLE
更新到1.10.15后出现的扩展报错：this.content is not a function(gameEvent.js)

### ISSUE THREAD

**Issue by ddeaat** [libccy/noname#1784]
## 错误描述
在更新到.15版本后这个拓展在发动技能时就会出现this.content is not a function的错误

### 使用的命令或代码

[神许邵_许邵ui.zip](https://github.com/user-attachments/files/16735392/_.ui.zip)

### 使用的环境、平台、设备

使用Android环境的1.6.4诗笺版，游戏版本为1.10.14/1.10.15

## 检查清单

- [ ] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by nonameShijian** [comment]
前几个issue里有
