### ISSUE TITLE
高顺+手杀周处不能把装备牌视为酒, 但是小乔+神关羽能把黑桃牌视为杀, 我怀疑后者是bug.

### ISSUE THREAD

**Issue by lolisix** [libccy/noname#179]
&emsp;&emsp;首先, 手杀周处+星黄忠组成双将, 不能使用骑射将装备牌当酒喝, 说明周处确实把装备牌的一切信息都视为了酒的对应信息. 
&emsp;&emsp;其次, 高顺+手杀周处, 或是手杀周处+高顺组成双将, 不能把装备牌视为杀, 说明「牌A视为牌B」中的牌A必须是游戏牌对应的实体牌中的信息为牌A, 被其他效果修改后的信息不能参与「视为」的运算.
&emsp;&emsp;同理, 我测试了改版神孙权+界高顺与界高顺+改版神孙权的组合, 界高顺将酒的点数视为K, 为字母, 改版神孙权将点数为字母的牌视为调剂盐梅. 经过实验, 两人组成双将, 无法使点数为2的酒视为调剂盐梅. 这也验证了被其他效果修改的牌的信息不参与「视为」运算.
![](https://s2.loli.net/2023/07/29/KaQxPnW6vzFgms3.png)
![](https://s2.loli.net/2023/07/29/oEVqLPf2xMth8Ui.png)
&emsp;&emsp;但是, 无论是小乔+神关羽组成双将, 还是神关羽+小乔组成双将, 都能够做到把黑桃牌视为杀, 从少数服从多数来看, 后者应该是bug.

&emsp;&emsp;虽说高顺+手杀周处与界高顺+改版神孙权中的牌没法被进行2次视为操作应用还能用「一张牌不能被二次转化」给糊弄过去, 但是我在规则集里面没有找到相关描述, 我不承认这种糊弄描述. 而且规则集中关于「视为」操作与「转化」描述解释得不是很清晰. 按照规则集中的「转化」定义, 在神关羽的武魂中, 对应实体牌为红桃牌的杀根本就不是转化牌. 
![](https://s2.loli.net/2023/07/29/v2igUGTsOcYoRBy.png)
![](https://s2.loli.net/2023/07/29/EgQw7bOrKPRucFh.png)
![](https://s2.loli.net/2023/07/29/rWVQEcH52vZa9FS.png)

**Comment by lolisix** [comment]
关于<<"牌A视为牌B"中的牌A必须是游戏牌对应的实体牌中的信息为牌A, 被其他效果修改后的信息不能参与"视为"的运算>>, 我还有一个铁证可以证明其为真.
李异谢旌的斗阵能够把黑色基本牌视为决斗, 高顺的禁酒能够把酒视为杀. 经过测试, 李异谢旌-高顺组成双将, 是把黑色酒视为杀, 高顺-李异谢旌组成双将, 是把黑色酒视为决斗. 如果"牌A视为牌B"中的牌A的信息可以让其他效果修改后的信息覆盖, 那么李异谢旌与高顺无论以什么顺序组合称双将, 都应该把黑色酒视为决斗, 这是因为决斗不是酒, 无法具有禁酒的效果.
![](https://s2.loli.net/2023/07/29/Cah4H3oPUYKe8qd.png)
![](https://s2.loli.net/2023/07/29/NBibUgDR6GhKeyE.png)

**Comment by Spmario233** [comment]
没出现无限递归调用就不用管（
