### ISSUE TITLE
1.10.15.1 联机大厅 Upgrade Required

### ISSUE THREAD

**Issue by kahvia-d** [libccy/noname#1815]
## 问题描述
通过docker部署noname后，访问联机大厅时显示“Upgrade Required”。
![fad18974b1d5ba06c20227f4e3cd6881](https://github.com/user-attachments/assets/898b1efa-ed21-4f86-a76d-fa600b88190a)

## 问题信息

游戏版本：1.10.15.1
服务器端口已放行，且阿里云安全组也已配置规则放行端口。
### 使用的命令或代码

[您的教程](https://github.com/libccy/noname/blob/master/docker/docker.md)
### 使用的环境、平台、设备

操作系统：Ubuntu 22.04
设备：阿里云服务器

### 版本信息

Linux Ubuntu 22.04

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by nonameShijian** [comment]
@Rintim

**Comment by Rintim** [comment]
无名杀的联机大厅（应该叫这个名字吗）是直接以WebSocket的形式展现的，而以网页的形式访问则会返回426，也就是`Upgrade Required`

如果无名杀本身能正常访问联机服务器就不用管，正常的WebSocket连接并不会出现该问题

**Comment by ICE-GB** [comment]
@Rintim 突然想到另一个问题，目前是不是只支持ip端口连接，不支持域名并且带有路径连接，例如`https://a.b.com/noname-server`指向联机端口

**Comment by Rintim** [comment]
> @Rintim 突然想到另一个问题，目前是不是只支持ip端口连接，不支持域名并且带有路径连接，例如`https://a.b.com/noname-server`指向联机端口
@ICE-GB  域名是支持的，路径确实不支持；无名杀不关注给定的是不是域名，但端口号是直接由`:`断开判断的，且如果不存在端口则会在末尾添加`:8080`，故路径是无法在目前无名杀中实现的

顺带，无名杀的联机用到的协议是`Websocket`，所以不需要带`https://`；无名杀会自动添加scheme，你也可以自行添加`ws://`或`wss://`
