### ISSUE TITLE
四象封印标刘璋技能错误

### ISSUE THREAD

**Issue by TruthCat** [libccy/noname#1891]
## 问题描述
四象封印标刘璋技能“引戈”错误，应该是“你可以令一名其他角色交给你一张牌”，无名杀里是"你可以令一名其他角色摸两张牌"。
### 使用的命令或代码

无
### 使用的环境、平台、设备

pc win10

### 版本信息
win64

## 检查清单

- [ x] 此问题没有在其他issue(议题)中出现
- [ x] 我已将无名杀本体更新为最新版本
- [ x] 我已将所有扩展更新为最新版本
- [ x] 我填写了上面所有必要的信息

**Comment by xizifu** [comment]
更新版本，这个一个月前就改了

**Comment by TruthCat** [comment]
就是最新版本，依旧是错的，还请大佬确认一下。

**Comment by TruthCat** [comment]
1.10.15.1的版本

**Comment by xizifu** [comment]
#1803 你可以查看下，这个已经修复了，我意思你可以跟进下pr版本

**Comment by TruthCat** [comment]
十分感谢大佬解惑，我明白了。
