### ISSUE TITLE
九鼎谋孙尚香结姻bug

### ISSUE THREAD

**Issue by bldwang** [libccy/noname#1934]
## 错误信息
九鼎谋孙尚香结姻选项二应为：2.你回复1点体力并获得所有“妆”，然后减1点体力上限，变更势力至吴，删去此选项。实际上选项二在被选择后未被删除，导致在游戏中九鼎谋孙尚香的体力上限会反复减少，直到为0。
另：无名杀在补充线下九鼎武将的时候疑似遗漏了晋张春华？

## 检查清单

- [ ] 此问题没有在其他issue(议题)中出现
- [ ] 我已将无名杀本体更新为最新版本
- [ ] 我已将所有扩展更新为最新版本
- [ ] 我填写了上面所有必要的信息

**Comment by AstralBarrage** [comment]
![5fe59a95-b4fc-460f-a515-733d490da70b](https://github.com/user-attachments/assets/3bc165c0-8a22-43fd-875c-a12a232856e4)
实体卡并没有删去此选项

**Comment by bldwang** [comment]
好的，那这应是网络制图的错。
