### ISSUE TITLE
求助各位大佬，idea pull下项目，怎么debug啊

### ISSUE THREAD

**Issue by KOFKOY** [libccy/noname#212]
对node.js不太熟悉，不知道怎么启动、调试。这个项目还能打包安卓吗，怎么打包的，求大佬们指点
想自己diy武将玩

**Comment by nonameShijian** [comment]
这个是纯浏览器项目，可以直接双击index.html在浏览器玩，用浏览器的控制台来debug。至于打包成电脑和手机版是为了有本地文件读写功能的。
