### ISSUE TITLE
v1.10.16 安卓无法下载扩展

### ISSUE THREAD

**Issue by RancherJie** [libccy/noname#2140]
## 问题描述
在使用安卓下载扩展，无法下载
![Screenshot_20241208_143123](https://github.com/user-attachments/assets/a7458efc-6c9d-40bf-9aa4-29afbbf57af9)
![Screenshot_20241208_144432](https://github.com/user-attachments/assets/eed7a5da-01e5-46c0-b7b8-89ffd8b42d0b)
下述仓库地址在电脑中可以正常下载安装扩展，在使用安卓启动的无名杀无法正常下载扩展。其他仓库也有类似问题。

## 问题信息
无名杀版本v1.10.16
仓库地址 https://gitee.com/RancherJie/noname_xingbei_extension/raw/master/

### 使用的命令或代码
无

### 使用的环境、平台、设备
电脑使用由理启动器启动无名杀
安卓使用诗笺启动器和由理启动器启动无名杀
各客户端均为本Issus提出时最新版

### 版本信息
电脑 win10 64位
手机 安卓14

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by nonameShijian** [comment]
经查证，是下载函数有问题，过后会修

**Comment by nonameShijian** [comment]
已修
