### ISSUE TITLE
神郭嘉双形态皮肤觉醒不触发手刹觉醒特效

### ISSUE THREAD

**Issue by kunkunntm** [libccy/noname#2152]
## 问题描述
神郭嘉双形态皮肤觉醒不触发手刹觉醒特效
## 问题信息

神郭嘉双形态皮肤除了手刹不触发觉醒特效，十周年和ol的觉醒特效都能触发
### 使用的命令或代码

name: '神郭嘉/倚星折月/XingXiang',
				x: [0,-0.38],
				y: [0,0.32],
				scale: 0.45,
                //speed: 1,
				//action: 'DaiJi',
				gongji: {
					name: '神郭嘉/倚星折月/XingXiang',
					x: [0,0.41],
			     	y: [0,0.63],
			     	scale: 0.35,
				},
				beijing: {
					name: '神郭嘉/倚星折月/BeiJing',
					scale: 0.3,
					x: [0, 0.5],
					y: [0, 0.5]
				},
				audio: {
					skill: '神郭嘉/倚星折月/audio',
					card: '神郭嘉/倚星折月/audio',
				},
				special: {
					觉醒: {
						name: 'shen_guojia/倚星折月2/XingXiang-1',
					},
					condition: {
						juexingji: {
							transform: "觉醒",
							effect: 'shaohui',
							//play: 'play',
						},
					},
				},
			},
			倚星折月2:{
				name: '神郭嘉/倚星折月2/XingXiang-1',
				x: [0,-0.42],
			   	y: [0,0.51],
				scale: 0.4,
                //speed: 1,
				//action: 'DaiJi',
				gongji: {
					name: '神郭嘉/倚星折月2/XingXiang-1',
					x: [0,0.46],
			      	y: [0,0.61],
			    	scale: 0.4,
				},
				audio: {
					skill: '神郭嘉/倚星折月2/audio',
					card: '神郭嘉/倚星折月2/audio',
				},
				beijing: {
					name: '神郭嘉/倚星折月2/BeiJing-1',
					scale: 0.3,
					x: [0, 0.5],
					y: [0, 0.5]
				},
			},
        },### 使用的环境、平台、设备

红米k70，本体v1.10.16

### 版本信息
本体v1.10.16

## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [x] 我已将无名杀本体更新为最新版本
- [x] 我已将所有扩展更新为最新版本
- [x] 我填写了上面所有必要的信息

**Comment by nonameShijian** [comment]
特效方面不在更新计划内，也不是本项目提供的内容

**Comment by 1937475624** [comment]
物种多样性.jpg

**Comment by kunkunntm** [comment]
> 物种多样性.jpg

你母亲不在达尔文的物种进化论里？
