### ISSUE TITLE
should commit package.json,  and add node_modules in .gitignore

### ISSUE THREAD

**Issue by leoendless** [libccy/noname#22]
``node_modules`` should not be commit,
Add a README or develop guide for other developers to contribute

**Comment by ttma1046** [comment]
https://github.com/libccy/noname/pull/28

**Comment by Spmario233** [comment]
很抱歉在两年之后才回复您。
node_modules文件夹是用来配合server,js文件，自行开设联机服务器的。为方便起见，放在了同一个仓库中。
该仓库是用于游戏内热更新使用的下载点，而非打包客户端用，因此无需整合package.json。
