### ISSUE TITLE
官网网盘维护一下？？

### ISSUE THREAD

**Issue by Kartmatu** [libccy/noname#25]
https://pan.baidu.com/s/1c8bzDc
已经无法下载了

**Comment by g5239277** [comment]
附议

**Comment by wqk317** [comment]
我添加了分流, 发了[PR](https://github.com/wqk317/noname), 没人merge, 你们可以先下, @Kartmatu @g5239277

**Comment by Spmario233** [comment]
狗百度不给面子 我能咋办
