### ISSUE TITLE
关于untrigger的问题

### ISSUE THREAD

**Issue by kuangshen04** [libccy/noname#260]
<img width="650" alt="3ee683be169e4137c47ebee8197ece3f" src="https://github.com/libccy/noname/assets/76837499/4d49de58-5003-4026-bc0d-41a5d8fa0e5d"><br>
call(this,arguments)等价于call(this,true)，这样写不仅会对可读性产生影响，而且使前面的arg1,arg2失去了意义<br>
<img width="486" alt="288d6f2570a622bf219f1447e3b42bb6" src="https://github.com/libccy/noname/assets/76837499/4cbd3475-bbfe-4aa8-9c57-9e845ff1c081"><br>
而鉴于untrigger不写参数就会无事发生（我猜本体很多时候也没注意到），<br>
<img width="211" alt="e4cd6e8844ccb61ad3196ae1d52c5c59" src="https://github.com/libccy/noname/assets/76837499/53b66a01-4707-464b-bcab-e4df77bc8033"><br>
我的建议是：<br>
1、call改成apply（废话）；<br>
2、untrigger的第一个参数默认值设为true

**Comment by kuangshen04** [comment]
还有就是neutralize的第一个参数event和untrigger的第一个参数冲突了，也要处理一下

**Comment by Tipx-L** [comment]
PR了
fix #262
