### ISSUE TITLE
基于无名杀做了个扩展，希望可以放入无名杀的扩展列表里

### ISSUE THREAD

**Issue by BlackAndWhiteScallion** [libccy/noname#27]
《东方流星夜》，东方project为主，动漫为辅的大型扩展，新系统，新武将，新卡牌，新模式，完全崭新好玩的游戏体验！

不传代码，在简介里贴上这个游戏链接就行：

游戏链接是这个，点开就能玩：
http://bws.coding.me/Night-of-Shooting-Stars

辛苦开发组大家的努力了，祝无名杀越来越好！

**Comment by 514DNA** [comment]
真滴牛批，跪了
你这连game.js都改了，我只会改extension.js
你是怎么做到改game.js然后游戏不报错的，我随便动一点game.js的代码游戏就运行不了了
我也做了个东方扩展……就是单纯写武将技能，43个东方武将和一些其他动漫的

**Comment by BlackAndWhiteScallion** [comment]
只要有报错就好说嘛，找着报错位置改就行了，多改几次总会成功的。
代码这东西就是肝，肝到肝出来为止嘛。
是同道中人太好了，握手握手，我也是40个东方加一堆其他动漫的，加群来群里面聊聊？
群号就在游戏里头。

**Comment by mgsqz** [comment]
游戏很不错，改动真大啊，敢动基本框架的都是大佬。
网页版火狐浏览器下这个对话框是要逼死强迫症。。。chrome内核的没有该问题。。。IE内核直接不能玩
![捕获](https://user-images.githubusercontent.com/31202580/73807636-2bccc600-4808-11ea-9f5a-a1a6e005a9ff.JPG)

**Comment by BlackAndWhiteScallion** [comment]
> 游戏很不错，改动真大啊，敢动基本框架的都是大佬。
> 网页版火狐浏览器下这个对话框是要逼死强迫症。。。chrome内核的没有该问题。。。IE内核直接不能玩
> ![捕获](https://user-images.githubusercontent.com/31202580/73807636-2bccc600-4808-11ea-9f5a-a1a6e005a9ff.JPG)

IE没救的。火狐的话我去想想办法……谢谢反馈的说

**Comment by Spmario233** [comment]
开新项目吧 扩展不是用来放这个的
