### ISSUE TITLE
与"弃牌阶段"和"弃牌阶段内"有关的问题, "其没有弃置牌"是否特指弃置其的牌? 

### ISSUE THREAD

**Issue by lolisix** [libccy/noname#280]
三谷良一的蜕皮描述说: 你装备区的牌于弃牌阶段内计入手牌上限.
首先, 技能中只说明了装备区的牌计入手牌上限, 没有说明装备牌能如手牌般弃置, 我认为没有类似的话, 就不能弃置装备牌.
其次, 技能中是"弃牌阶段内"都计入手牌上限, 那么如果向我上面的描述一样, 是"装备牌如手牌般弃置", 那么如果三谷良一在弃牌阶段内被使用刺杀后, 可以使用闪, 再弃置装备牌来抵消刺杀的效果, 但实际上不能这样做.
所以我认为蜕皮的真正描述是: 你装备区的牌于**弃牌阶段**计入手牌上限, 且**装备区里的装备牌能如手牌般弃置**.

我还测试了类似的3D刘宏, 刘宏的党锢说, 其他角色的弃牌阶段, 其装备牌视为手牌.
目前没发现结算与描述不符的情况.
比如, 其他角色在弃牌阶段内受到伤害后, 其确实不能用展示装备牌来代替展示手牌.

兔子两只2的孙坚有一个技能藏玺, 技能的描述不够清晰, 经过我测试, 应该为: 主公技,其他吴势力角色的弃牌阶段结束时,若其**于弃牌阶段**弃置了至少两张牌,则可以选择判定.

-------

"其没有弃置牌"是否特指弃置其的牌? 这个问题是我在看夺江的描述想到的, 夺江要求一名角色"于其弃牌阶段内没有弃置过牌", 我就在想, 如果这个角色没有弃置自己的牌, 而是弃置了其他人的牌, 那能否执行后续效果? 不过我目前还没有想到要如何让一名角色在弃牌阶段内既不弃置自己的牌, 又不弃置其他人的牌.

**Comment by Spmario233** [comment]
描述问题都是小问题
