### ISSUE TITLE
主程大大，能否添加change.log呢？便于查看各个版本的更新内容哈^o^

### ISSUE THREAD

**Issue by gxcdream** [libccy/noname#30]
想自己做一些改写和扩展，又担心错过主分支的最新修改内容，因此，要是有个change.log记录各个版本的更新内容，就可以便于merge和功能取舍，想必是极好的哈。

**Comment by Spmario233** [comment]
我觉得吧...看commit change就行了...

**Comment by gxcdream** [comment]
大佬，commit change看起来比较抽象呢，最好多加一些改动说明哈
