### ISSUE TITLE
界左慈化身技能重复bug修复

### ISSUE THREAD

**Issue by mgsqz** [libccy/noname#36]
化身技能函数添加化身时候都是遍历一遍所有可获得的化身，没有排除已获得的化身，故会出现化身重复的现象
目前把化身初始化放在游戏开始就不会出现类似问题，代码修改如下（加粗部分为添加的代码，并需要在函数addHuashen里删除加粗的字段）：
			rehuashen_init:{
				trigger:{
					global:'gameDrawAfter',
					player:'enterGame',
				},
				forced:true,
				popup:false,
				content:function(){
					**var list=[];
					for(i in lib.character){
						list.push(i);
					}
					list.randomSort();
					_status.characterlist=list.slice(0);
					if(!player.storage.rehuashen) return;
					//_status.characterlist.randomSort();**
					lib.skill.rehuashen.addHuashens(player,3);
					player.syncStorage('rehuashen');
					player.markSkill('rehuashen');
					var next=game.createEvent('rehuashen');
					next.player=player;
					next._trigger=trigger;
					next.triggername='rehuashen';
					next.setContent(lib.skill.rehuashen.content);
				},
			},

**Comment by Spmario233** [comment]
Bug反馈已经收到 但你TM不能把这个步骤放到addHuashen的检测里吗

**Comment by Spmario233** [comment]
> Bug反馈已经收到 但你TM不能把这个步骤放到addHuashen的检测里吗

在那个步骤检测即将获得的化身是否已经拥有 拥有就跳过

**Comment by mgsqz** [comment]
版本更新错了，原来大大已经修复了
