### ISSUE TITLE
subPlayer函数无法调用扩展武将图片

### ISSUE THREAD

**Issue by chen079** [libccy/noname#374]
subPlayer函数无法调用扩展武将图片，也许需要进行适配

**Comment by nonameShijian** [comment]
目前测试可以调用扩展武将图片了
![image](https://github.com/user-attachments/assets/172eb6dc-85e8-4aa0-bf56-18b6439ce404)
![image](https://github.com/user-attachments/assets/6a20938a-06fe-4243-a66b-6a7f280d7f34)
