### ISSUE TITLE
https访问无名杀时联机功能不可用

### ISSUE THREAD

**Issue by zjl88858** [libccy/noname#43]
RT，

我将无名杀上传在一个在线服务器中以方便和朋友一起玩，
当使用HTTP访问时一切正常，使用HTTPS时联机会提示“无效的联机地址”。

谢谢。

**Comment by whsyourdaddy** [comment]
你可以参考我的博客：
<a href="https://blog.angelo.org.cn/%e9%85%8d%e7%bd%ae%e6%97%a0%e5%90%8d%e6%9d%80%e5%9c%a8https%e4%b8%8b%e8%81%94%e6%9c%ba%e6%b8%b8%e6%88%8f/">配置无名杀在HTTPS下联机游戏</a>

不懂之处可留言。
