### ISSUE TITLE
希望能自定义项目地址

### ISSUE THREAD

**Issue by dyxang** [libccy/noname#45]
因为国内也有很多项目托管服务，github在国内访问实在太慢。clone 到国内 更新和下载的速度都会快些  
Coding 使用的是腾讯服务器  
Gitee 亮点是可以从 Github 导入，还支持更新（即远程仓库更新后对应的gitee仓库也可更新）  
另外，有一些Github加速服务，如https://g.ioiox.com/ 等。

**Comment by Spmario233** [comment]
有coding啊 并且已经是当前的最优解了
Gitee不支持直接下载1MB以上的文件（需要登录） 无法用于游戏内下载

**Comment by dyxang** [comment]
> 有coding啊 并且已经是当前的最优解了
> Gitee不支持直接下载1MB以上的文件（需要登录） 无法用于游戏内下载

emmm，其实只是个例子，不过 Github 完全可以用  jsDelivr 的链接替换（虽然短时间内有缓存时间），因为总所周知 jsDelivr 与 Github 仓库是同步更新的，不仅国外服务器丰富，而且在国内还有服务器（Coding 免费版是新加坡的貌似）
