### ISSUE TITLE
1.9.104中似乎bug修复了一部分, 但宴诛改的受伤增加只持续一轮.

### ISSUE THREAD

**Issue by Spmario233** [libccy/noname#51]
1.9.104中似乎bug修复了一部分, 但宴诛改的受伤增加只持续一轮.
希望后续版本修复!

_Originally posted by @luminous030 in https://github.com/libccy/noname/issues/49#issuecomment-699573252_

只持续一轮是设计本意

**Comment by luminous030** [comment]
> 1.9.104中似乎bug修复了一部分, 但宴诛改的受伤增加只持续一轮.
> 希望后续版本修复!
> 
> _Originally posted by @luminous030 in [#49 (comment)](https://github.com/libccy/noname/issues/49#issuecomment-699573252)_
> 
> 只持续一轮是设计本意

之前的技能介绍是没有"只持续一轮"这个限制的, 刚才又打开看看, 发现多了这个限制...
