### ISSUE TITLE
使用game.addPlayer后对新的player，若这个player触发player.gain就会弹出错误框

### ISSUE THREAD

**Issue by Zioywishing** [libccy/noname#523]
我自己看了下应该是game.addPlayer中不会给新的player赋playerid，导致18699行id被赋值undefine，进而导致错误，我在game.addPlayer中加入
```
player.playerid = get.id()
game.playerMap[player.playerid] = player
```
之后问题似乎解决。。。

**Comment by universe-st** [comment]
addPlayer后为其赋值ID的时机在各个模式里。我这里是推荐addPlayer之后手动赋值一次ID。
