### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by xiaoas** [libccy/noname#54]
黑锋骑士 天启牌包括了所有装备 且数量达到四便获得胜利
界孙坚 无法选择自己
旧夏侯氏 孝德可以看见所有技能（而非武将牌上的）
杨仪 度断 只能弃置手牌
虚空之影 额外回合获得的镜像牌无法正确摸牌/给予潜行
张春华 伤势只能弃置手牌与描述不合

**Comment by Spmario233** [comment]
1.下个版本修复
2.描述问题 下个版本修复
3.你孝德的是神山识？
4.5.6.下个版本修复
