### ISSUE TITLE
关于木牛流马与丈八蛇矛的连锁问题

### ISSUE THREAD

**Issue by heijuanmao** [libccy/noname#55]
尊敬的无名杀维护者们，感谢您的辛勤付出，有几个关于木牛流马的问题反馈如下：
在问询是否打出杀、闪的响应过程中，目前流程是先从“辎”中选择（此时无法选择手牌），若选择取消，则从手牌中选择（此时无法选择“辎”），这导致在装备丈八情况下，无法将一张手牌与一张“辎”一同当做杀打出，受影响的还有小关张“父魂”、袁绍“乱击”以及其他类似技能的响应（猜测，未经测试），出牌阶段用丈八使用杀也无法分别选择手牌和“辎”。

总结：现有响应流程无法满足“将一张手牌与一张‘辎’，视为一张牌使用或打出”。

**Comment by Spmario233** [comment]
我早就想改了 但是一直没啥头绪
想要不出bug去修改的话几乎要对整个无名杀做出翻天覆地的改版 所以把它当成村规就好
