### ISSUE TITLE
界孙坚武烈技能说明（吹毛求疵请原谅）

### ISSUE THREAD

**Issue by heijuanmao** [libccy/noname#57]
尊敬的无名杀维护者：
10.27版对武烈技能说明的修改：将“有「烈」的角色受到伤害时”改为“有「烈」的其他角色受到伤害时”，目的应该是表达「烈」不能给自己，我认为“其他”二字应加在“你可以失去任意点体力并指定等量的角色”处比较准确，也就是“你可以失去任意点体力并指定等量的其他角色”。请您参考。

**Comment by Spmario233** [comment]
下个版本修
