### ISSUE TITLE
bug: 界吴国太描述错误

### ISSUE THREAD

**Issue by xiaoas** [libccy/noname#59]
[reganlu_info](https://github.com/libccy/noname/blob/e16c401511e9f076d92b60f9c913447421005464/character/refresh.js#7850): 
'出牌阶段限一次，你可以选择装备区牌数之差的绝对值不小于X的两名角色或包含你在内的两名角色，然后交换这两名角色装备区内的牌。（X为你已损失的体力值）'
其中“绝对值不小于X的”应当改为”绝对值不大于X的两“

**Comment by Spmario233** [comment]
下个版本修
