### ISSUE TITLE
如何编写武将？

### ISSUE THREAD

**Issue by YoshimiSakuka** [libccy/noname#6]
我没在网上找到教程。先fork下，我再仔细找找。

**Comment by YoshimiSakuka** [comment]
我甚至翻了一遍代码，仍然猜不出来一半这个程度。请作者进行一些必要注释。（比如，player类有哪些方法，event类有哪些方法，等等）

**Comment by Lucilor** [comment]
你可以先参照自带的武将代码写一些类似的技能
