### ISSUE TITLE
在技能询问中使用木牛流马下的牌

### ISSUE THREAD

**Issue by lziad** [libccy/noname#60]
关于技能询问中无法使用“辎”的问题，之前也有一些类似反馈（如 #55 ），这里提供一个解决方案希望抛砖引玉，即在发起技能询问时若满足条件，将辎加入手牌区供选择，点击取消或确定后再移除。具体代码实现和文档请见[这里](https://github.com/lziad/noname-sgs#%E5%AE%8C%E6%95%B4%E7%9A%84%E6%9C%A8%E7%89%9B%E6%B5%81%E9%A9%AC%E4%BD%BF%E7%94%A8%E4%BD%93%E9%AA%8C)。

**Comment by heijuanmao** [comment]
感谢这位热心的高手对反馈的回应，真心希望您有机会深入的参与无名杀维护。
另，看到您对木牛流马代码运行的理解，还想请求一事，您可否制作出十周年版本木牛流马？即最多5张辎，满5张后不可继续放入，也不可直接移动。（出牌阶段限一次，你可以将一张手牌扣置于你装备区里的【木牛流马】下，**至多五张**。若如此做，你可以将此装备移动到一名其他角色的装备区里；你可以将此装备下的牌如手牌般使用或打出。）

**Comment by lziad** [comment]
谢谢您的肯定，我可以帮忙进行维护，不知道您觉得是我在这里提交 pull request 的形式比较好还是怎么样，但如果交 pull request 的话可能会和您那边增加的代码冲突（这也是我这边自己弄了个仓库的原因）。
关于新版木牛流马，[这个 commit](https://github.com/lziad/noname-sgs/commit/bee40a77b855a47e0822ce854143db0363718a5d) 直接加了一张新卡 muniu_new 供参考，实际上只改了原来 muniu_skill 的 filter
```javascript
				filter:function(event,player){
					var muniu=player.getEquip(5);
					if(muniu&&muniu.cards&&muniu.cards.length>=5) return false;
					return player.countCards('h')>0;
				},
```
判断当前“辎”是否已达到五张，若达到则不可发动后续效果。目前简单测试来看没有问题。

**Comment by Spmario233** [comment]
思路很不错√
然而本人至少接下来的数月之内，并没有对其进行修改的想法。（AB1st的汉化为优先项目，没有精力去对所有的技能进行调整）
等该项目完成之后将会转向此内容的修改，但不会直接采用您的代码，而是采取更加通用的判断方法（从而兼容★甘宁等角色）。
木牛流马5张牌的限制，在本人看来是Online狗策划提高活动场难度的行为，故本人不会进行修改。
另外上面那位回复的人，我并不认识。

**Comment by lziad** [comment]
OK没问题。我之前没注意回复者，有些误会了，不好意思（笑）

**Comment by Spmario233** [comment]
…我好像更新完之后忘了关闭这个issue了？
木牛流马/星甘宁【锦帆】已经修改完成，AB1st的汉化也已经初步完成。
