### ISSUE TITLE
没有找到服务端node_modules文件夹和game文件夹下的server.js

### ISSUE THREAD

**Issue by ZhaoLizz** [libccy/noname#66]
我想在阿里云上搭建一个服务端，查询到 #53 提到 

> 去阿里云之类的地方开一台VPS服务器（或者用自家电脑开端口映射之类的），将node_modules文件夹和game文件夹下的server.js放在同一文件夹内并上传到服务器，打开命令行，运行
node server.js
，然后去游戏里输入这台服务器的IP地址即可

然而工程文件里面没有找到node_modeules 和 server.js文件。请问有解决方法和教程吗？感谢作者！

**Comment by Spmario233** [comment]
为了防止源代码被滥用，已经从仓库中移除了相关文件。
去QQ群的离线包/完整包里面找找吧

**Comment by Spmario233** [comment]
为了防止源代码被滥用，已经从仓库中移除了相关文件。
去QQ群的离线包/完整包里面找找吧
