### ISSUE TITLE
bug 对决-自由

### ISSUE THREAD

**Issue by Jencese** [libccy/noname#67]
对决场自由模式中有替补的情况下，替补武将上场就能继承伤害的问题，经常会出现满血曹丕翻人的情况，1.4左右的版本不会继承伤害，我觉得武将阵亡后结束伤害计算比较合适。

对决-自由，有替补的情况，武将阵亡到底算不算有武将离场的问题。
毋丘俭在阵亡3个武将以上，只要场上满员，仍不能觉醒。同样的还有关索，只能对同一位置的武将发动一次征南（不管那个位置上的武将是第几次濒死）。羊徽瑜的技能只要全场满员就可以不弃牌发动。
另外一种情况就是诸葛诞，有武将阵亡就能加上限，即使全场满员。
神司马懿和张松这些写〈杀死〉的技能没有问题。
建议都可以改成诸葛诞这种判断机制。

3，手刹朱然打审配伤害后，审配下回合烈直依然可以发动。审配在自己回合受到伤害，下回合应该不可以发动烈直吧（看技能文字意思），建议改一下

**Comment by Spmario233** [comment]
替补武将是死者苏生 而非换人再来
这个问题解决起来比较棘手 暂时没有完美的方案（因为还有魏延这种不管人在不在都能吸血的将）
虽然我不知道具体是什么原因 但可以把新11的代码复制过来 粗略地解决这个问题

**Comment by Spmario233** [comment]
至于问题2
官方为什么要移除这些模式，或者在这些模式限制将池？
没人玩固然是原因，但这些原因不也很重要？
