### ISSUE TITLE
希望能优化一下网络请求机制

### ISSUE THREAD

**Issue by StarOnTheSky** [libccy/noname#673]
hello，我是fastgit(fgit.cf)的管理员。今天在分析日志时，我发现来自 libccy/noname 仓库的请求数量巨大，从2023/11/25 00:00:00到22:06:44共计收到了1913762个请求，另外一个仓库 libccy/noname-extension 共计收到了191687个请求，两者共计占据了我们镜像站raw部分访问量的98.7%。尽可放心，这些请求**没有**让服务器过载。不过，我有点好奇无名杀的文件下载机制是如何运作的，是否能够通过部分打包下载的方式减少请求数量，这样有助于降低 github 对镜像服务器 IP 风控/速率限制的概率。

**Comment by Spmario233** [comment]
感谢您的反馈。
目前游戏每次检查更新都会请求一次update.js，然后再单独请求仓库内每个文件进行下载。
我们会暂时将游戏内的默认请求方式切换到CSDN的GitCode，随后再进行优化。

**Comment by StarOnTheSky** [comment]
> 感谢您的反馈。 目前游戏每次检查更新都会请求一次update.js，然后再单独请求仓库内每个文件进行下载。 我们会暂时将游戏内的默认请求方式切换到CSDN的GitCode，随后再进行优化。

考虑到本仓库需求很大，我们计划为相关仓库提供服务端git镜像，服务器硬盘可以装下master分支的文件，应该能够在减少回源的情况下满足更新需求。😗

**Comment by nonameShijian** [comment]
> > 感谢您的反馈。 目前游戏每次检查更新都会请求一次update.js，然后再单独请求仓库内每个文件进行下载。 我们会暂时将游戏内的默认请求方式切换到CSDN的GitCode，随后再进行优化。
> 
> 考虑到本仓库需求很大，我们计划为相关仓库提供服务端git镜像，服务器硬盘可以装下master分支的文件，应该能够在减少回源的情况下满足更新需求。😗

hello，我也是开发组成员之一，最近打算重构项目的更新模块。

我们打算: 
1. 限制**自动检测更新**的功能使每次客户端关闭前只能自动检测更新一次
2. 使用api.github.com来获取项目的更新公告、获取新版本对比旧版本不同的“离线包”(离线包随tag上传)，然后使用github的代理网站来下载离线包(例: https://github.com/libccy/noname/archive/refs/tags/v1.10.10.zip)
3. 但是跨版本更新，“离线包”会出现缺素材的情况。在用户手动授权后，将会再次请求api.github.com相应的文件列表功能(例: https://api.github.com/repos/libccy/noname/contents/${path})，然后通过sha对比来生成需要增量更新的文件列表。通过服务器生成返回的文件列表来进行更新。

所以第三条可能需要您
