### ISSUE TITLE
挑战模式无法选用神邓艾神貂蝉神贾诩

### ISSUE THREAD

**Issue by XiaCizhaogedade** [libccy/noname#678]
挑战模式无法选用神邓艾神貂蝉神贾诩 （我这个是用自己创建了个扩展然后自己编辑的这三个武将的方式 添加的），另外神邓艾技能险进游戏提示为险峻 
![Screenshot_20231126_161811_yuri nakamura noname_android](https://github.com/libccy/noname/assets/147239458/99462a36-df30-4f92-975e-575244b61043)

>

**Comment by XiaCizhaogedade** [comment]
> 挑战模式无法选用神邓艾神貂蝉神贾诩（我这个是用自己创建了个扩展然后自己编辑的这三个武将的方式 添加的） ，另外神邓艾技能险进游戏提示为险峻 ![Screenshot_20231126_161811_yuri nakamura noname_android](https://private-user-images.githubusercontent.com/147239458/285640802-99462a36-df30-4f92-975e-575244b61043.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTA3ODQsIm5iZiI6MTcwMDk5MDQ4NCwicGF0aCI6Ii8xNDcyMzk0NTgvMjg1NjQwODAyLTk5NDYyYTM2LWRmMzAtNGY5Mi05NzVlLTU3NTI0NGI2MTA0My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQwOTIxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmQ3MzgxMjNjM2E5MmUxNDg2ZThmZjczYWM3NzIxZmJhMTY3OWQ5ZmQyMWNlYWI4MWI5M2MwNTY5MTBjYjZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tY32ZeUOlvd5e7t_enxC0ddeozKR4hr6sYxBfu2B_5U) ![Screenshot_20231126_161811_yuri nakamura noname_android](https://private-user-images.githubusercontent.com/147239458/285640806-791446ee-b23b-4e5a-a7f4-ebc83f577ccd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTA3ODQsIm5iZiI6MTcwMDk5MDQ4NCwicGF0aCI6Ii8xNDcyMzk0NTgvMjg1NjQwODA2LTc5MTQ0NmVlLWIyM2ItNGU1YS1hN2Y0LWViYzgzZjU3N2NjZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQwOTIxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTEzNzhiMWVjYmEyZDY1MThhMGMyNmQyZTE5YTIxMmYxMzc1YWFjMmFlNTYwYmVkNGE4MDA4NTg4NzIzY2FkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A4R78BjJ4qzvSujTZsDV3LfR1kPqjmiTQPex4c0IVDc)

**Comment by universe-st** [comment]
这几个角色在此模式下是禁用的。
