### ISSUE TITLE
如何脱离客户端在网页安装扩展，访问网页资源即可加载扩展？

### ISSUE THREAD

**Issue by SunSwallow** [libccy/noname#70]
目前教程中对于扩展的安装需要基于客户端，那么请问能不能直接将扩展安装在源代码中呢？
或者有人有已经安装好UI扩展的源代码版本吗？

**Comment by adeFuLoDgu** [comment]
改game/game.js的arena:function，強制無名殺遊戲讀取擴展，我自行修改（註解load custom extension start部分）：[game.js](https://github.com/adeFuLoDgu/noname/blob/master/game/game.js)，效果：[noname](https://adefulodgu.github.io/noname)。

**Comment by SunSwallow** [comment]
感谢~
