### ISSUE TITLE
用aws的linux虚拟机建造私服

### ISSUE THREAD

**Issue by ZiWenWangCS** [libccy/noname#72]
我想问一下怎么用aws里面的linux虚拟机建造私服跟朋友玩. 我在linux服务器上面有node_modules 和server.js 并运行了node server.js. 然后在打开了无名杀的index.html里面输入了相应的 public ip4 地址但是链接不上去. 我也读了这个 https://aws.amazon.com/premiumsupport/knowledge-center/connect-http-https-ec2/ (I host a website on an EC2 instance. How do I allow my users to connect on HTTP (80) or HTTPS (443)?). 我也开启了8080端口. 但还是连不上. 有没有办法解决?
![Selection_036](https://user-images.githubusercontent.com/40008057/135531983-1dd09bb7-b6c3-4766-94ee-a46314067dc2.png)

**Comment by zjl88858** [comment]
看起来你只是在安全组开了？
先netstat -anp |grep 8080确认启动的没问题
然后如果是红帽系 systemctl stop firewalld

**Comment by ZiWenWangCS** [comment]
谢谢！我没把防火墙关掉。现在我可以链接上了
