### ISSUE TITLE
网页版无法连接联机大厅

### ISSUE THREAD

**Issue by RasdSky** [libccy/noname#73]
网页版在大部分浏览器上无法连接到联机大厅，原因是浏览器阻止了混合内容
![81a84b8e7c71d35551790860cade614](https://user-images.githubusercontent.com/18697554/141053127-9cb500e5-9639-4c04-a58e-4d366c84d0d7.png)
部分浏览器可以通过设置允许不安全的内容来连接，手机端的大多数浏览器无法设置，望解决

**Comment by Spmario233** [comment]
可wss它不能用没有域名的ip连接啊

**Comment by RainEggplant** [comment]
我弄了一个 [无名杀网页版的修改版本](https://github.com/RainEggplant/noname-pwa)（支持 PWA）。联机时默认采用 wss 连接，但也支持 ws 连接。对于 ws 因为安全策略被阻止的问题，如果手机端浏览器基于 Chromium 的话是可以设置的，可以参考我写的这个 [说明文档](https://github.com/RainEggplant/noname-pwa/blob/master/allow_mixed_content.md)。

**Comment by RainEggplant** [comment]
@Spmario233 如果有计划加入对 wss 连接的额外支持，我可以提个 pr
