### ISSUE TITLE
显示更新地址有误

### ISSUE THREAD

**Issue by Streamer-stars** [libccy/noname#731]
游戏版本：1.10.5
GitHub下载的手机版
点击检查游戏更新后弹出alert弹窗，显示更新地址有误。
![244882548-51772474-5e99-4e4d-b615-b6ce4bd28fea](https://github.com/libccy/noname/assets/76718993/8143a3c3-9a4e-43d0-831b-8b3fcd1c2b3a)

**Comment by holicli** [comment]
通用-更新地址好像默认是csdn，换成github就好了
