### ISSUE TITLE
新版本技能优先度priority的判断似乎有问题

### ISSUE THREAD

**Issue by Zioywishing** [libccy/noname#795]
同一个时机不同priority的技能不能被正确地按priority被释放，而是像是priority一致一样要求玩家选择下一个触发的技能。在/noname/library/element/content.js的2028行加上
event.choice = event.choice.sort((a,b)=>{a.priority >= b.priority}).filter(n=>n.priority == event.choice[0].priority)
后可以暂时性缓解这个问题。

**Comment by universe-st** [comment]
#797 fixed
