### ISSUE TITLE
推荐苏婆大神及各路高手了解一下小程序版三国杀里的一种PvE模式三国战纪（赤壁之战）

### ISSUE THREAD

**Issue by heijuanmao** [libccy/noname#80]
首先感谢苏婆大神一直以来的更新维护。

最近接触到**小程序版三国杀中的PvE模式”三国战纪“**（我是从美团中找到的，活动场），如果您还没试过，推荐您了解一下，理由如下：

一、三国杀Roguelike，从一个常规武将开始闯关模式，自主选择前进路径（战斗、奇遇、卡牌屋、店铺、boss战等），每次战斗获得货币（可在游玩过程中买卡、合成卡、买宝物等）、随机新技能三选一（玩法核心，最多保留四个技能，新技能可替换），以及根据战斗过程出的分数。
二、并没有一定能通关的套路，有重复游玩的价值。
三、受众：**固定每天10次挑战机会，玩家没法深度研究，所以如有机会希望能在无名杀中看到**。
四、说着容易做着难，若真做还需多人协助摸索关卡地方武将信息，困难重重，只是提议给各路高手参考，希望大神莫得困扰。

无论如何请您先尝试一下，有其可取之处，但请不要沉迷影响维护进度哟。

**Comment by Spmario233** [comment]
懒
