### ISSUE TITLE
更新后加载失败

### ISSUE THREAD

**Issue by Streamer-stars** [libccy/noname#800]
在GitHub上下载的手机版，之前可以正常使用，但今天更新后点击重新启动就无法使用了
![1705328433196](https://github.com/libccy/noname/assets/76718993/b082cd33-003d-4b6a-bc49-a7cf124d49ec)
卸载原版本在GitHub上重新下载新版本后仍然弹出此弹窗

**Comment by Streamer-stars** [comment]
更换兼容版后解决

**Comment by XiaoXiaoLui** [comment]
网页版也碰到这个问题，最新chrome版本（120.0.6099.217）也弹这个窗口提示
