### ISSUE TITLE
Mac os端客户端 遗失无法更新

### ISSUE THREAD

**Issue by sakura6227** [libccy/noname#82]
mac端app还打算更新嘛

**Comment by Spmario233** [comment]
没设备 没法调试捏

**Comment by rxliuli** [comment]
> 没设备 没法调试捏

吾辈有 mac m2 的设备，是否可以添加客户端，吾辈可以帮忙测试。另外还想问一下现在的客户端是是使用什么框架制作的？

**Comment by dzy1997** [comment]
其实如果有m1/m2 mac的话是可以直接下载TestFlight运行iOS版的

**Comment by rxliuli** [comment]
几个月后，吾辈再次想玩一会，发现仍然没有 mac 客户端，于是自行构建了一个 mac release

https://1drv.ms/u/s!AqTwKbfzs-vykYg9oiGMCwXL3_Qf3g?e=lVSUEU
