### ISSUE TITLE
noname-server.exe启动index.js报错

### ISSUE THREAD

**Issue by XiaoXiaoLui** [libccy/noname#829]
![无名杀1](https://github.com/libccy/noname/assets/22817664/89087da6-cb9d-4e92-a296-0b2fa7371c07)
![无名杀2](https://github.com/libccy/noname/assets/22817664/4d79ec6a-7d22-4d80-8694-9822a83b5d72)
启动noname-server.exe网页弹框报错如上。
最新的chrome浏览器。

**Comment by XiaoXiaoLui** [comment]
git代码版本 9698106cd400e074565c97f3ee6acce7c6bbca9f

**Comment by nonameShijian** [comment]
用最新版本试试
