### ISSUE TITLE
115.1版本界张春华技能有bug

### ISSUE THREAD

**Issue by wenq1217** [libccy/noname#88]
绝情技能正常情况下应当把伤害转变为体力流逝，但目前的版本会直接将原伤害再次计算一次，例如界张春华酒杀空牌的曹叡，正常情况下曹叡会流失两点体力，不能触发恢拓，当前版本会出现张春华造成4点伤害且曹叡被救回后依然能触发恢拓的情况。

**Comment by Spmario233** [comment]
绝情这一次伤害本身是不会被更改的
你猜猜为什么界张春华单挑打卖血将不如标张春华
