### ISSUE TITLE
十常侍和曹爽的技能互动问题

### ISSUE THREAD

**Issue by WilliamFaulkner2023** [libccy/noname#918]
![屏幕截图 2024-02-05 175135](https://github.com/libccy/noname/assets/145753148/22cc7c99-7e9a-4f25-b54c-a6cadb70c582)

不知道这算不算BUG，十常侍选择了死亡这个技能...直接就把曹爽干掉了...

**Comment by Spmario233** [comment]
不算Bug。
手杀羊徽瑜吃到十常侍的技能之后，也会因为没有常侍而直接死。
