### ISSUE TITLE
能够在技能后续结算中使用杀的武将的技能描述是不是有问题?

### ISSUE THREAD

**Issue by lolisix** [libccy/noname#93]
比如界刘备, 他用仁德使用虚拟杀, 这张虚拟杀由于在仁德的结算中, 所以此杀在非空闲时间点里, 所以此杀应该不计入出牌阶段的使用次数且无次数限制. 但是在实际执行时, 刘备没有办法使用仁德打出第二张杀, 所以是不是技能描述中缺少了"计入次数限制"字样? 据说老杀的界仁德是有这个字样的.
http://bug.sanguosha.com/?mod=view&id=57808
根据上面这个反馈, 在老杀的武将池中, 还可能有这种问题的技能还有这些 :
潘凤-狂斧
刘封-陷嗣 
钟繇-活墨
潘淑-锦织 
卧龙凤雏-游龙 

另外, 还有一个武将, 我认为技能描述需要加字, 就是手杀的界曹真, 在第一个R出现时, 就应该指明R是一个关系, 而不是在后面的aRb中指明R是一个关系.

**Comment by lolisix** [comment]
对了, 按理来说, 刘备使用的虚拟杀应该还有特别标注一下有距离限制, 不过我看现在官方好像把"虚拟杀无距离限制"这个规则给吞了, 默认虚拟杀是有距离限制的了, 反而无距离限制的虚拟杀才会被特殊标注.

**Comment by lolisix** [comment]
不过只要有借刀杀人这张锦囊存在, "出牌阶段的非空闲时间点使用的杀不计入次数限制且无次数限制"这条规则官方就吞不了.

**Comment by Spmario233** [comment]
这个问题是狗卡自己蜀黑，一直不肯让仁德的【杀】不计入次数限制的结果。
潘凤在无名杀一直无次数限制，不受影响。
其他方法使用的【杀】本质和“将XX当做XX使用”的流程一致，因此受次数限制理所应当。
