### ISSUE TITLE
1.9.117.2 国战相关bug

### ISSUE THREAD

**Issue by CodexYt** [libccy/noname#96]
## Bug

-   国钟会【权计】，受到伤害后即可发动，没有次数限制，与“每回合限一次”描述不符（尝试做过的修改详见[关闭的PR](https://github.com/libccy/noname/pull/95/commits/cf28cebe525c4de47787a451ba6492655eca6620#diff-0b0b932980221dd29ede3bce38cce2290c4c085e503cc1cc2f6039d7121a4a7d)）
-   单机国战模式开启“替换君主”选项后，联机创建国战房间时未弹出“替换君主”选项，且联机游戏中满足替换君主武将的条件时，仍然无法替换君主武将牌

## 语音

-   国许攸【成略】【恃才】技能语音弄反了
-   国钟会【权计】【排异】技能语音弄反了

## 可能的优化

-   国左棻【诏颂】的各项子技能，能否用武将旁的扩展（extension）标明哪些尚未发动？

**Comment by Spmario233** [comment]
语音问题不做优化
