### ISSUE TITLE
张让滔乱技能描述不一致

### ISSUE THREAD

**Issue by FibonaccciYan** [libccy/noname#997]
![QQ图片20240227232450](https://github.com/libccy/noname/assets/58576758/be97943b-dd8e-42d0-b5a8-7c3c624acb04)

如图所示，张让的滔乱技能在描述时是“交给你一张不同类别的牌”，但是在技能发动时的提示却是”交给你一张类别相同的牌“，两处文本不一致，分别在 yijiang.js 中2786和2801行，建议修改这个文本上的小bug

**Comment by Spmario233** [comment]
已修复
